//! Gap-fill vocabulary: common Japanese words found missing from
//! `vocab.rs` + `vocab_extended.rs` + `vocab_large.rs` during a manual
//! audit (2026-07-25) — question words most notably were entirely absent.
//! Hand-curated, not auto-generated. See `docs/MODEL.md` section 1.4.

use crate::vocab::{Category, Pos, VocabEntry};

pub fn build_gapfill_vocab() -> Vec<VocabEntry> {
    vec![
        // ── 의문사 (question words) — completely absent before this file ──
        VocabEntry::new("何", "なに", Pos::Noun, Category::Abstract),
        VocabEntry::new("何か", "なにか", Pos::Noun, Category::Abstract),
        VocabEntry::new("誰", "だれ", Pos::Noun, Category::Abstract),
        VocabEntry::new("誰か", "だれか", Pos::Noun, Category::Abstract),
        VocabEntry::new("どなた", "どなた", Pos::Noun, Category::Abstract),
        VocabEntry::new("どこ", "どこ", Pos::Noun, Category::Place),
        VocabEntry::new("どこか", "どこか", Pos::Noun, Category::Place),
        VocabEntry::new("いつ", "いつ", Pos::Noun, Category::Time),
        VocabEntry::new("いつか", "いつか", Pos::Noun, Category::Time),
        VocabEntry::new("なぜ", "なぜ", Pos::Adverb, Category::Abstract),
        VocabEntry::new("どうして", "どうして", Pos::Adverb, Category::Abstract),
        VocabEntry::new("何で", "なんで", Pos::Adverb, Category::Abstract),
        VocabEntry::new("いくつ", "いくつ", Pos::Noun, Category::Abstract),
        VocabEntry::new("いくら", "いくら", Pos::Noun, Category::Shopping),
        VocabEntry::new("どれ", "どれ", Pos::Noun, Category::Abstract),
        VocabEntry::new("どの", "どの", Pos::Noun, Category::Abstract),
        VocabEntry::new("どちら", "どちら", Pos::Noun, Category::Abstract),
        VocabEntry::new("どっち", "どっち", Pos::Noun, Category::Abstract),
        VocabEntry::new("どんな", "どんな", Pos::Noun, Category::Abstract),
        VocabEntry::new("どう", "どう", Pos::Adverb, Category::Abstract),
        VocabEntry::new("どうやって", "どうやって", Pos::Adverb, Category::Abstract),
        VocabEntry::new("何人", "なんにん", Pos::Noun, Category::Abstract),
        VocabEntry::new("何時", "なんじ", Pos::Noun, Category::Time),
        VocabEntry::new("何歳", "なんさい", Pos::Noun, Category::Abstract),
        VocabEntry::new("何月", "なんがつ", Pos::Noun, Category::Time),
        VocabEntry::new("何日", "なんにち", Pos::Noun, Category::Time),
        VocabEntry::new("何曜日", "なんようび", Pos::Noun, Category::Time),

        // ── 숫자/조수사 (numbers, counters) ──
        VocabEntry::new("一", "いち", Pos::Noun, Category::Abstract),
        VocabEntry::new("二", "に", Pos::Noun, Category::Abstract),
        VocabEntry::new("三", "さん", Pos::Noun, Category::Abstract),
        VocabEntry::new("四", "よん", Pos::Noun, Category::Abstract),
        VocabEntry::new("五", "ご", Pos::Noun, Category::Abstract),
        VocabEntry::new("六", "ろく", Pos::Noun, Category::Abstract),
        VocabEntry::new("七", "なな", Pos::Noun, Category::Abstract),
        VocabEntry::new("八", "はち", Pos::Noun, Category::Abstract),
        VocabEntry::new("九", "きゅう", Pos::Noun, Category::Abstract),
        VocabEntry::new("十", "じゅう", Pos::Noun, Category::Abstract),
        VocabEntry::new("百", "ひゃく", Pos::Noun, Category::Abstract),
        VocabEntry::new("千", "せん", Pos::Noun, Category::Abstract),
        VocabEntry::new("万", "まん", Pos::Noun, Category::Abstract),
        VocabEntry::new("零", "れい", Pos::Noun, Category::Abstract),
        VocabEntry::new("一つ", "ひとつ", Pos::Counter, Category::Abstract),
        VocabEntry::new("二つ", "ふたつ", Pos::Counter, Category::Abstract),
        VocabEntry::new("三つ", "みっつ", Pos::Counter, Category::Abstract),
        VocabEntry::new("四つ", "よっつ", Pos::Counter, Category::Abstract),
        VocabEntry::new("五つ", "いつつ", Pos::Counter, Category::Abstract),
        VocabEntry::new("六つ", "むっつ", Pos::Counter, Category::Abstract),
        VocabEntry::new("七つ", "ななつ", Pos::Counter, Category::Abstract),
        VocabEntry::new("八つ", "やっつ", Pos::Counter, Category::Abstract),
        VocabEntry::new("九つ", "ここのつ", Pos::Counter, Category::Abstract),
        VocabEntry::new("十", "とお", Pos::Counter, Category::Abstract),
        VocabEntry::new("一人", "ひとり", Pos::Counter, Category::Abstract),
        VocabEntry::new("二人", "ふたり", Pos::Counter, Category::Abstract),
        VocabEntry::new("三人", "さんにん", Pos::Counter, Category::Abstract),
        VocabEntry::new("一回", "いっかい", Pos::Counter, Category::Abstract),
        VocabEntry::new("一番", "いちばん", Pos::Noun, Category::Abstract),
        VocabEntry::new("半分", "はんぶん", Pos::Noun, Category::Abstract),

        // ── 시간/요일 (time, days — some already present, filling remainder) ──
        VocabEntry::new("週末", "しゅうまつ", Pos::Noun, Category::Time),
        VocabEntry::new("平日", "へいじつ", Pos::Noun, Category::Time),
        VocabEntry::new("今週", "こんしゅう", Pos::Noun, Category::Time),
        VocabEntry::new("来週", "らいしゅう", Pos::Noun, Category::Time),
        VocabEntry::new("先週", "せんしゅう", Pos::Noun, Category::Time),
        VocabEntry::new("今月", "こんげつ", Pos::Noun, Category::Time),
        VocabEntry::new("来月", "らいげつ", Pos::Noun, Category::Time),
        VocabEntry::new("先月", "せんげつ", Pos::Noun, Category::Time),
        VocabEntry::new("毎週", "まいしゅう", Pos::Noun, Category::Time),
        VocabEntry::new("毎月", "まいつき", Pos::Noun, Category::Time),
        VocabEntry::new("毎年", "まいとし", Pos::Noun, Category::Time),
        VocabEntry::new("誕生日", "たんじょうび", Pos::Noun, Category::Time),
        VocabEntry::new("今夜", "こんや", Pos::Noun, Category::Time),
        VocabEntry::new("今朝", "けさ", Pos::Noun, Category::Time),
        VocabEntry::new("さっき", "さっき", Pos::Adverb, Category::Time),
        VocabEntry::new("後で", "あとで", Pos::Adverb, Category::Time),
        VocabEntry::new("最近", "さいきん", Pos::Adverb, Category::Time),
        VocabEntry::new("最初", "さいしょ", Pos::Noun, Category::Time),
        VocabEntry::new("最後", "さいご", Pos::Noun, Category::Time),

        // ── 사람/관계 (people, relationships) ──
        VocabEntry::new("名前", "なまえ", Pos::Noun, Category::Abstract),
        VocabEntry::new("お名前", "おなまえ", Pos::Noun, Category::Abstract),
        VocabEntry::new("友達", "ともだち", Pos::Noun, Category::Family),
        VocabEntry::new("親友", "しんゆう", Pos::Noun, Category::Family),
        VocabEntry::new("彼氏", "かれし", Pos::Noun, Category::Family),
        VocabEntry::new("彼女", "かのじょ", Pos::Noun, Category::Family),
        VocabEntry::new("恋人", "こいびと", Pos::Noun, Category::Family),
        VocabEntry::new("赤ちゃん", "あかちゃん", Pos::Noun, Category::Family),
        VocabEntry::new("大人", "おとな", Pos::Noun, Category::Family),
        VocabEntry::new("先輩", "せんぱい", Pos::Noun, Category::Family),
        VocabEntry::new("後輩", "こうはい", Pos::Noun, Category::Family),
        VocabEntry::new("お客さん", "おきゃくさん", Pos::Noun, Category::Family),
        VocabEntry::new("隣人", "りんじん", Pos::Noun, Category::Family),

        // ── 색깔 (colors) ──
        VocabEntry::new("色", "いろ", Pos::Noun, Category::Color),
        VocabEntry::new("赤", "あか", Pos::Noun, Category::Color),
        VocabEntry::new("青", "あお", Pos::Noun, Category::Color),
        VocabEntry::new("黄色", "きいろ", Pos::Noun, Category::Color),
        VocabEntry::new("緑", "みどり", Pos::Noun, Category::Color),
        VocabEntry::new("紫", "むらさき", Pos::Noun, Category::Color),
        VocabEntry::new("茶色", "ちゃいろ", Pos::Noun, Category::Color),
        VocabEntry::new("灰色", "はいいろ", Pos::Noun, Category::Color),
        VocabEntry::new("金色", "きんいろ", Pos::Noun, Category::Color),
        VocabEntry::new("銀色", "ぎんいろ", Pos::Noun, Category::Color),
        VocabEntry::new("水色", "みずいろ", Pos::Noun, Category::Color),

        // ── 신체 (body) ──
        VocabEntry::new("頭", "あたま", Pos::Noun, Category::Body),
        VocabEntry::new("顔", "かお", Pos::Noun, Category::Body),
        VocabEntry::new("目", "め", Pos::Noun, Category::Body),
        VocabEntry::new("耳", "みみ", Pos::Noun, Category::Body),
        VocabEntry::new("鼻", "はな", Pos::Noun, Category::Body),
        VocabEntry::new("口", "くち", Pos::Noun, Category::Body),
        VocabEntry::new("歯", "は", Pos::Noun, Category::Body),
        VocabEntry::new("首", "くび", Pos::Noun, Category::Body),
        VocabEntry::new("肩", "かた", Pos::Noun, Category::Body),
        VocabEntry::new("腕", "うで", Pos::Noun, Category::Body),
        VocabEntry::new("手", "て", Pos::Noun, Category::Body),
        VocabEntry::new("指", "ゆび", Pos::Noun, Category::Body),
        VocabEntry::new("胸", "むね", Pos::Noun, Category::Body),
        VocabEntry::new("お腹", "おなか", Pos::Noun, Category::Body),
        VocabEntry::new("背中", "せなか", Pos::Noun, Category::Body),
        VocabEntry::new("腰", "こし", Pos::Noun, Category::Body),
        VocabEntry::new("脚", "あし", Pos::Noun, Category::Body),
        VocabEntry::new("足", "あし", Pos::Noun, Category::Body),
        VocabEntry::new("膝", "ひざ", Pos::Noun, Category::Body),
        VocabEntry::new("髪", "かみ", Pos::Noun, Category::Body),
        VocabEntry::new("心", "こころ", Pos::Noun, Category::Body),

        // ── 감정/상태 (emotions, states) ──
        VocabEntry::new("結婚", "けっこん", Pos::Noun, Category::Abstract),
        VocabEntry::new("恋愛", "れんあい", Pos::Noun, Category::Abstract),
        VocabEntry::new("夢", "ゆめ", Pos::Noun, Category::Abstract),
        VocabEntry::new("秘密", "ひみつ", Pos::Noun, Category::Abstract),
        VocabEntry::new("約束", "やくそく", Pos::Noun, Category::Abstract),
        VocabEntry::new("問題", "もんだい", Pos::Noun, Category::Abstract),
        VocabEntry::new("答え", "こたえ", Pos::Noun, Category::Abstract),
        VocabEntry::new("質問", "しつもん", Pos::Noun, Category::Abstract),
        VocabEntry::new("理由", "りゆう", Pos::Noun, Category::Abstract),
        VocabEntry::new("意味", "いみ", Pos::Noun, Category::Abstract),
        VocabEntry::new("方法", "ほうほう", Pos::Noun, Category::Abstract),
        VocabEntry::new("経験", "けいけん", Pos::Noun, Category::Abstract),
        VocabEntry::new("趣味", "しゅみ", Pos::Noun, Category::Hobby),
        VocabEntry::new("性格", "せいかく", Pos::Noun, Category::Abstract),
        VocabEntry::new("気持ち", "きもち", Pos::Noun, Category::Emotion),
        VocabEntry::new("気分", "きぶん", Pos::Noun, Category::Emotion),
        VocabEntry::new("元気", "げんき", Pos::NaAdjective, Category::Emotion),
        VocabEntry::new("大丈夫", "だいじょうぶ", Pos::NaAdjective, Category::Emotion),
        VocabEntry::new("残念", "ざんねん", Pos::NaAdjective, Category::Emotion),
        VocabEntry::new("心配", "しんぱい", Pos::NaAdjective, Category::Emotion),
        VocabEntry::new("安心", "あんしん", Pos::NaAdjective, Category::Emotion),
        VocabEntry::new("興味", "きょうみ", Pos::Noun, Category::Emotion),
        VocabEntry::new("自信", "じしん", Pos::Noun, Category::Emotion),
        VocabEntry::new("感謝", "かんしゃ", Pos::Noun, Category::Emotion),
        VocabEntry::new("幸せ", "しあわせ", Pos::NaAdjective, Category::Emotion),

        // ── 형용사 (i-adjectives / na-adjectives) ──
        VocabEntry::new("面白い", "おもしろい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("楽しい", "たのしい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("悲しい", "かなしい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("嬉しい", "うれしい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("怖い", "こわい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("難しい", "むずかしい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("簡単", "かんたん", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("便利", "べんり", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("大変", "たいへん", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("素敵", "すてき", Pos::NaAdjective, Category::Emotion),
        VocabEntry::new("可愛い", "かわいい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("格好いい", "かっこいい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("優しい", "やさしい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("忙しい", "いそがしい", Pos::IAdjective, Category::Work),
        VocabEntry::new("眠い", "ねむい", Pos::IAdjective, Category::Body),
        VocabEntry::new("痛い", "いたい", Pos::IAdjective, Category::Body),
        VocabEntry::new("寂しい", "さびしい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("恥ずかしい", "はずかしい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("羨ましい", "うらやましい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("速い", "はやい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("遅い", "おそい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("重い", "おもい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("軽い", "かるい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("強い", "つよい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("弱い", "よわい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("明るい", "あかるい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("暗い", "くらい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("近い", "ちかい", Pos::IAdjective, Category::Place),
        VocabEntry::new("遠い", "とおい", Pos::IAdjective, Category::Place),
        VocabEntry::new("広い", "ひろい", Pos::IAdjective, Category::Place),
        VocabEntry::new("狭い", "せまい", Pos::IAdjective, Category::Place),
        VocabEntry::new("美味しい", "おいしい", Pos::IAdjective, Category::Food),
        VocabEntry::new("不味い", "まずい", Pos::IAdjective, Category::Food),
        VocabEntry::new("甘い", "あまい", Pos::IAdjective, Category::Food),
        VocabEntry::new("辛い", "からい", Pos::IAdjective, Category::Food),
        VocabEntry::new("苦い", "にがい", Pos::IAdjective, Category::Food),
        VocabEntry::new("酸っぱい", "すっぱい", Pos::IAdjective, Category::Food),
        VocabEntry::new("静か", "しずか", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("賑やか", "にぎやか", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("有名", "ゆうめい", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("親切", "しんせつ", Pos::NaAdjective, Category::Emotion),
        VocabEntry::new("上手", "じょうず", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("下手", "へた", Pos::NaAdjective, Category::Abstract),

        // ── 일반 동사 (common verbs) ──
        VocabEntry::new("分かる", "わかる", Pos::Verb, Category::Verb),
        VocabEntry::new("知る", "しる", Pos::Verb, Category::Verb),
        VocabEntry::new("思う", "おもう", Pos::Verb, Category::Verb),
        VocabEntry::new("考える", "かんがえる", Pos::Verb, Category::Verb),
        VocabEntry::new("忘れる", "わすれる", Pos::Verb, Category::Verb),
        VocabEntry::new("覚える", "おぼえる", Pos::Verb, Category::Verb),
        VocabEntry::new("待つ", "まつ", Pos::Verb, Category::Verb),
        VocabEntry::new("会う", "あう", Pos::Verb, Category::Verb),
        VocabEntry::new("笑う", "わらう", Pos::Verb, Category::Verb),
        VocabEntry::new("泣く", "なく", Pos::Verb, Category::Verb),
        VocabEntry::new("怒る", "おこる", Pos::Verb, Category::Verb),
        VocabEntry::new("驚く", "おどろく", Pos::Verb, Category::Verb),
        VocabEntry::new("始まる", "はじまる", Pos::Verb, Category::Verb),
        VocabEntry::new("終わる", "おわる", Pos::Verb, Category::Verb),
        VocabEntry::new("開ける", "あける", Pos::Verb, Category::Verb),
        VocabEntry::new("閉める", "しめる", Pos::Verb, Category::Verb),
        VocabEntry::new("入る", "はいる", Pos::Verb, Category::Verb),
        VocabEntry::new("出る", "でる", Pos::Verb, Category::Verb),
        VocabEntry::new("座る", "すわる", Pos::Verb, Category::Verb),
        VocabEntry::new("立つ", "たつ", Pos::Verb, Category::Verb),
        VocabEntry::new("走る", "はしる", Pos::Verb, Category::Verb),
        VocabEntry::new("歩く", "あるく", Pos::Verb, Category::Verb),
        VocabEntry::new("使う", "つかう", Pos::Verb, Category::Verb),
        VocabEntry::new("作る", "つくる", Pos::Verb, Category::Verb),
        VocabEntry::new("送る", "おくる", Pos::Verb, Category::Verb),
        VocabEntry::new("届く", "とどく", Pos::Verb, Category::Verb),
        VocabEntry::new("頑張る", "がんばる", Pos::Verb, Category::Verb),
        VocabEntry::new("続ける", "つづける", Pos::Verb, Category::Verb),
        VocabEntry::new("止める", "とめる", Pos::Verb, Category::Verb),
        VocabEntry::new("変える", "かえる", Pos::Verb, Category::Verb),
        VocabEntry::new("決める", "きめる", Pos::Verb, Category::Verb),
        VocabEntry::new("選ぶ", "えらぶ", Pos::Verb, Category::Verb),
        VocabEntry::new("探す", "さがす", Pos::Verb, Category::Verb),
        VocabEntry::new("見つける", "みつける", Pos::Verb, Category::Verb),
        VocabEntry::new("聞こえる", "きこえる", Pos::Verb, Category::Verb),
        VocabEntry::new("見える", "みえる", Pos::Verb, Category::Verb),
        VocabEntry::new("できる", "できる", Pos::Verb, Category::Verb),
        VocabEntry::new("なる", "なる", Pos::Verb, Category::Verb),
        VocabEntry::new("あげる", "あげる", Pos::Verb, Category::Verb),
        VocabEntry::new("もらう", "もらう", Pos::Verb, Category::Verb),
        VocabEntry::new("くれる", "くれる", Pos::Verb, Category::Verb),
        VocabEntry::new("手伝う", "てつだう", Pos::Verb, Category::Verb),
        VocabEntry::new("教える", "おしえる", Pos::Verb, Category::Verb),
        VocabEntry::new("習う", "ならう", Pos::Verb, Category::Verb),
        VocabEntry::new("運転する", "うんてんする", Pos::Verb, Category::Transport),
        VocabEntry::new("掃除する", "そうじする", Pos::Verb, Category::Home),
        VocabEntry::new("洗濯する", "せんたくする", Pos::Verb, Category::Home),
        VocabEntry::new("料理する", "りょうりする", Pos::Verb, Category::Food),
        VocabEntry::new("散歩する", "さんぽする", Pos::Verb, Category::Hobby),
        VocabEntry::new("旅行する", "りょこうする", Pos::Verb, Category::Hobby),

        // ── 인사말/표현 (greetings, common expressions) ──
        VocabEntry::new("お誕生日おめでとう", "おたんじょうびおめでとう", Pos::Expression, Category::Greeting),
        VocabEntry::new("お疲れ様", "おつかれさま", Pos::Expression, Category::Greeting),
        VocabEntry::new("お疲れ様でした", "おつかれさまでした", Pos::Expression, Category::Greeting),
        VocabEntry::new("よろしくお願いします", "よろしくおねがいします", Pos::Expression, Category::Greeting),
        VocabEntry::new("お大事に", "おだいじに", Pos::Expression, Category::Greeting),
        VocabEntry::new("お邪魔します", "おじゃまします", Pos::Expression, Category::Greeting),
        VocabEntry::new("頑張って", "がんばって", Pos::Expression, Category::Greeting),
        VocabEntry::new("大丈夫ですか", "だいじょうぶですか", Pos::Expression, Category::Greeting),
        VocabEntry::new("気をつけて", "きをつけて", Pos::Expression, Category::Greeting),
        VocabEntry::new("お先に失礼します", "おさきにしつれいします", Pos::Expression, Category::Greeting),
        VocabEntry::new("失礼します", "しつれいします", Pos::Expression, Category::Greeting),
        VocabEntry::new("申し訳ありません", "もうしわけありません", Pos::Expression, Category::Greeting),
        VocabEntry::new("ごめんなさい", "ごめんなさい", Pos::Expression, Category::Greeting),
        VocabEntry::new("お世話になります", "おせわになります", Pos::Expression, Category::Greeting),
        VocabEntry::new("お久しぶりです", "おひさしぶりです", Pos::Expression, Category::Greeting),
        VocabEntry::new("いらっしゃいませ", "いらっしゃいませ", Pos::Expression, Category::Greeting),
        VocabEntry::new("かしこまりました", "かしこまりました", Pos::Expression, Category::Greeting),
        VocabEntry::new("承知しました", "しょうちしました", Pos::Expression, Category::Greeting),
        VocabEntry::new("お疲れ", "おつかれ", Pos::Expression, Category::Greeting),
        VocabEntry::new("乾杯", "かんぱい", Pos::Expression, Category::Greeting),

        // ── 부사 (common adverbs) ──
        VocabEntry::new("とても", "とても", Pos::Adverb, Category::Abstract),
        VocabEntry::new("少し", "すこし", Pos::Adverb, Category::Abstract),
        VocabEntry::new("たくさん", "たくさん", Pos::Adverb, Category::Abstract),
        VocabEntry::new("全部", "ぜんぶ", Pos::Adverb, Category::Abstract),
        VocabEntry::new("いつも", "いつも", Pos::Adverb, Category::Time),
        VocabEntry::new("よく", "よく", Pos::Adverb, Category::Abstract),
        VocabEntry::new("たまに", "たまに", Pos::Adverb, Category::Time),
        VocabEntry::new("全然", "ぜんぜん", Pos::Adverb, Category::Abstract),
        VocabEntry::new("ちょっと", "ちょっと", Pos::Adverb, Category::Abstract),
        VocabEntry::new("すぐ", "すぐ", Pos::Adverb, Category::Time),
        VocabEntry::new("もう", "もう", Pos::Adverb, Category::Time),
        VocabEntry::new("まだ", "まだ", Pos::Adverb, Category::Time),
        VocabEntry::new("たぶん", "たぶん", Pos::Adverb, Category::Abstract),
        VocabEntry::new("きっと", "きっと", Pos::Adverb, Category::Abstract),
        VocabEntry::new("本当に", "ほんとうに", Pos::Adverb, Category::Abstract),
        VocabEntry::new("特に", "とくに", Pos::Adverb, Category::Abstract),
        VocabEntry::new("一緒に", "いっしょに", Pos::Adverb, Category::Abstract),
        VocabEntry::new("急に", "きゅうに", Pos::Adverb, Category::Abstract),
        VocabEntry::new("ゆっくり", "ゆっくり", Pos::Adverb, Category::Abstract),
        VocabEntry::new("はっきり", "はっきり", Pos::Adverb, Category::Abstract),
    ]
}
