//! Japanese vocabulary database for Hangul→Japanese IME
//!
//! This module provides a comprehensive vocabulary database storing (surface, reading) pairs
//! organized by part of speech (POS) and semantic category. The hangul field will be
//! auto-generated later by the kana_hangul converter.

use std::collections::HashMap;

/// Part of speech enumeration
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Pos {
    Noun,
    Verb,
    IAdjective,
    NaAdjective,
    Adverb,
    Particle,
    Conjunction,
    Expression,
    Counter,
    Suffix,
}

/// Semantic category enumeration
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Category {
    Greeting,
    Family,
    Food,
    Nature,
    Body,
    Place,
    Time,
    Transport,
    Work,
    School,
    Shopping,
    Health,
    Hobby,
    Emotion,
    Animal,
    Color,
    Technology,
    Home,
    Culture,
    Abstract,
    Particle,
    Verb,
}

/// Vocabulary entry containing surface form, reading, POS, and category
#[derive(Clone, Debug)]
pub struct VocabEntry {
    pub surface: &'static str,
    pub reading: &'static str,
    pub pos: Pos,
    pub category: Category,
}

impl VocabEntry {
    /// Create a new vocabulary entry
    pub fn new(surface: &'static str, reading: &'static str, pos: Pos, category: Category) -> Self {
        VocabEntry {
            surface,
            reading,
            pos,
            category,
        }
    }
}

/// Build the complete vocabulary database
pub fn build_vocab() -> Vec<VocabEntry> {
    vec![
        // === GREETINGS (15 words) ===
        VocabEntry::new("おはよう", "おはよう", Pos::Expression, Category::Greeting),
        VocabEntry::new("おはようございます", "おはようございます", Pos::Expression, Category::Greeting),
        VocabEntry::new("こんにちは", "こんにちは", Pos::Expression, Category::Greeting),
        VocabEntry::new("こんばんは", "こんばんは", Pos::Expression, Category::Greeting),
        VocabEntry::new("おやすみなさい", "おやすみなさい", Pos::Expression, Category::Greeting),
        VocabEntry::new("さようなら", "さようなら", Pos::Expression, Category::Greeting),
        VocabEntry::new("じゃあね", "じゃあね", Pos::Expression, Category::Greeting),
        VocabEntry::new("また明日", "またあした", Pos::Expression, Category::Greeting),
        VocabEntry::new("また明日ね", "またあしたね", Pos::Expression, Category::Greeting),
        VocabEntry::new("いってきます", "いってきます", Pos::Expression, Category::Greeting),
        VocabEntry::new("いってらっしゃい", "いってらっしゃい", Pos::Expression, Category::Greeting),
        VocabEntry::new("ただいま", "ただいま", Pos::Expression, Category::Greeting),
        VocabEntry::new("おかえり", "おかえり", Pos::Expression, Category::Greeting),
        VocabEntry::new("おはよう", "おはよう", Pos::Expression, Category::Greeting),
        VocabEntry::new("こんばんは", "こんばんは", Pos::Expression, Category::Greeting),

        // === FAMILY (20 words) ===
        VocabEntry::new("お母さん", "おかあさん", Pos::Noun, Category::Family),
        VocabEntry::new("お父さん", "おとうさん", Pos::Noun, Category::Family),
        VocabEntry::new("兄", "あに", Pos::Noun, Category::Family),
        VocabEntry::new("姉", "あね", Pos::Noun, Category::Family),
        VocabEntry::new("弟", "おとうと", Pos::Noun, Category::Family),
        VocabEntry::new("妹", "いもうと", Pos::Noun, Category::Family),
        VocabEntry::new("祖父", "そふ", Pos::Noun, Category::Family),
        VocabEntry::new("祖母", "そぼ", Pos::Noun, Category::Family),
        VocabEntry::new("叔父", "おじ", Pos::Noun, Category::Family),
        VocabEntry::new("叔母", "おば", Pos::Noun, Category::Family),
        VocabEntry::new("息子", "むすこ", Pos::Noun, Category::Family),
        VocabEntry::new("娘", "むすめ", Pos::Noun, Category::Family),
        VocabEntry::new("夫", "おっと", Pos::Noun, Category::Family),
        VocabEntry::new("妻", "つま", Pos::Noun, Category::Family),
        VocabEntry::new("家族", "かぞく", Pos::Noun, Category::Family),
        VocabEntry::new("親", "おや", Pos::Noun, Category::Family),
        VocabEntry::new("子ども", "こども", Pos::Noun, Category::Family),
        VocabEntry::new("母", "はは", Pos::Noun, Category::Family),
        VocabEntry::new("父", "ちち", Pos::Noun, Category::Family),
        VocabEntry::new("両親", "りょうしん", Pos::Noun, Category::Family),

        // === FOOD (50 words) ===
        VocabEntry::new("寿司", "すし", Pos::Noun, Category::Food),
        VocabEntry::new("ラーメン", "ラーメン", Pos::Noun, Category::Food),
        VocabEntry::new("天ぷら", "てんぷら", Pos::Noun, Category::Food),
        VocabEntry::new("焼肉", "やきにく", Pos::Noun, Category::Food),
        VocabEntry::new("味噌汁", "みそしる", Pos::Noun, Category::Food),
        VocabEntry::new("ご飯", "ごはん", Pos::Noun, Category::Food),
        VocabEntry::new("パン", "パン", Pos::Noun, Category::Food),
        VocabEntry::new("牛乳", "ぎゅうにゅう", Pos::Noun, Category::Food),
        VocabEntry::new("卵", "たまご", Pos::Noun, Category::Food),
        VocabEntry::new("野菜", "やさい", Pos::Noun, Category::Food),
        VocabEntry::new("果物", "くだもの", Pos::Noun, Category::Food),
        VocabEntry::new("りんご", "りんご", Pos::Noun, Category::Food),
        VocabEntry::new("みかん", "みかん", Pos::Noun, Category::Food),
        VocabEntry::new("魚", "さかな", Pos::Noun, Category::Food),
        VocabEntry::new("肉", "にく", Pos::Noun, Category::Food),
        VocabEntry::new("鶏肉", "とりにく", Pos::Noun, Category::Food),
        VocabEntry::new("豚肉", "ぶたにく", Pos::Noun, Category::Food),
        VocabEntry::new("牛肉", "ぎゅうにく", Pos::Noun, Category::Food),
        VocabEntry::new("塩", "しお", Pos::Noun, Category::Food),
        VocabEntry::new("砂糖", "さとう", Pos::Noun, Category::Food),
        VocabEntry::new("醤油", "しょうゆ", Pos::Noun, Category::Food),
        VocabEntry::new("味噌", "みそ", Pos::Noun, Category::Food),
        VocabEntry::new("酒", "さけ", Pos::Noun, Category::Food),
        VocabEntry::new("ビール", "ビール", Pos::Noun, Category::Food),
        VocabEntry::new("お茶", "おちゃ", Pos::Noun, Category::Food),
        VocabEntry::new("コーヒー", "コーヒー", Pos::Noun, Category::Food),
        VocabEntry::new("水", "みず", Pos::Noun, Category::Food),
        VocabEntry::new("ジュース", "ジュース", Pos::Noun, Category::Food),
        VocabEntry::new("ケーキ", "ケーキ", Pos::Noun, Category::Food),
        VocabEntry::new("チョコレート", "チョコレート", Pos::Noun, Category::Food),
        VocabEntry::new("アイスクリーム", "アイスクリーム", Pos::Noun, Category::Food),
        VocabEntry::new("麺", "めん", Pos::Noun, Category::Food),
        VocabEntry::new("スープ", "スープ", Pos::Noun, Category::Food),
        VocabEntry::new("サラダ", "サラダ", Pos::Noun, Category::Food),
        VocabEntry::new("フルーツ", "フルーツ", Pos::Noun, Category::Food),
        VocabEntry::new("ナッツ", "ナッツ", Pos::Noun, Category::Food),
        VocabEntry::new("バター", "バター", Pos::Noun, Category::Food),
        VocabEntry::new("チーズ", "チーズ", Pos::Noun, Category::Food),
        VocabEntry::new("トマト", "トマト", Pos::Noun, Category::Food),
        VocabEntry::new("玉ねぎ", "たまねぎ", Pos::Noun, Category::Food),
        VocabEntry::new("じゃがいも", "じゃがいも", Pos::Noun, Category::Food),
        VocabEntry::new("人参", "にんじん", Pos::Noun, Category::Food),
        VocabEntry::new("キャベツ", "キャベツ", Pos::Noun, Category::Food),
        VocabEntry::new("バナナ", "バナナ", Pos::Noun, Category::Food),
        VocabEntry::new("苺", "いちご", Pos::Noun, Category::Food),
        VocabEntry::new("ぶどう", "ぶどう", Pos::Noun, Category::Food),
        VocabEntry::new("レモン", "レモン", Pos::Noun, Category::Food),
        VocabEntry::new("オレンジ", "オレンジ", Pos::Noun, Category::Food),
        VocabEntry::new("スイカ", "スイカ", Pos::Noun, Category::Food),
        VocabEntry::new("メロン", "メロン", Pos::Noun, Category::Food),

        // === NATURE (35 words) ===
        VocabEntry::new("山", "やま", Pos::Noun, Category::Nature),
        VocabEntry::new("川", "かわ", Pos::Noun, Category::Nature),
        VocabEntry::new("海", "うみ", Pos::Noun, Category::Nature),
        VocabEntry::new("空", "そら", Pos::Noun, Category::Nature),
        VocabEntry::new("雲", "くも", Pos::Noun, Category::Nature),
        VocabEntry::new("雨", "あめ", Pos::Noun, Category::Nature),
        VocabEntry::new("雪", "ゆき", Pos::Noun, Category::Nature),
        VocabEntry::new("風", "かぜ", Pos::Noun, Category::Nature),
        VocabEntry::new("桜", "さくら", Pos::Noun, Category::Nature),
        VocabEntry::new("花", "はな", Pos::Noun, Category::Nature),
        VocabEntry::new("木", "き", Pos::Noun, Category::Nature),
        VocabEntry::new("森", "もり", Pos::Noun, Category::Nature),
        VocabEntry::new("草", "くさ", Pos::Noun, Category::Nature),
        VocabEntry::new("月", "つき", Pos::Noun, Category::Nature),
        VocabEntry::new("星", "ほし", Pos::Noun, Category::Nature),
        VocabEntry::new("太陽", "たいよう", Pos::Noun, Category::Nature),
        VocabEntry::new("石", "いし", Pos::Noun, Category::Nature),
        VocabEntry::new("土", "つち", Pos::Noun, Category::Nature),
        VocabEntry::new("火", "ひ", Pos::Noun, Category::Nature),
        VocabEntry::new("島", "しま", Pos::Noun, Category::Nature),
        VocabEntry::new("湖", "こ", Pos::Noun, Category::Nature),
        VocabEntry::new("滝", "たき", Pos::Noun, Category::Nature),
        VocabEntry::new("虹", "にじ", Pos::Noun, Category::Nature),
        VocabEntry::new("霧", "きり", Pos::Noun, Category::Nature),
        VocabEntry::new("冬", "ふゆ", Pos::Noun, Category::Nature),
        VocabEntry::new("春", "はる", Pos::Noun, Category::Nature),
        VocabEntry::new("夏", "なつ", Pos::Noun, Category::Nature),
        VocabEntry::new("秋", "あき", Pos::Noun, Category::Nature),
        VocabEntry::new("波", "なみ", Pos::Noun, Category::Nature),
        VocabEntry::new("砂", "すな", Pos::Noun, Category::Nature),
        VocabEntry::new("泥", "どろ", Pos::Noun, Category::Nature),
        VocabEntry::new("岩", "いわ", Pos::Noun, Category::Nature),
        VocabEntry::new("洞窟", "どうくつ", Pos::Noun, Category::Nature),
        VocabEntry::new("谷", "たに", Pos::Noun, Category::Nature),
        VocabEntry::new("峰", "みね", Pos::Noun, Category::Nature),

        // === BODY (25 words) ===
        VocabEntry::new("頭", "あたま", Pos::Noun, Category::Body),
        VocabEntry::new("顔", "かお", Pos::Noun, Category::Body),
        VocabEntry::new("目", "め", Pos::Noun, Category::Body),
        VocabEntry::new("耳", "みみ", Pos::Noun, Category::Body),
        VocabEntry::new("鼻", "はな", Pos::Noun, Category::Body),
        VocabEntry::new("口", "くち", Pos::Noun, Category::Body),
        VocabEntry::new("歯", "は", Pos::Noun, Category::Body),
        VocabEntry::new("手", "て", Pos::Noun, Category::Body),
        VocabEntry::new("足", "あし", Pos::Noun, Category::Body),
        VocabEntry::new("指", "ゆび", Pos::Noun, Category::Body),
        VocabEntry::new("腕", "うで", Pos::Noun, Category::Body),
        VocabEntry::new("肩", "かた", Pos::Noun, Category::Body),
        VocabEntry::new("背中", "せなか", Pos::Noun, Category::Body),
        VocabEntry::new("胸", "むね", Pos::Noun, Category::Body),
        VocabEntry::new("お腹", "おなか", Pos::Noun, Category::Body),
        VocabEntry::new("心臓", "しんぞう", Pos::Noun, Category::Body),
        VocabEntry::new("血", "ち", Pos::Noun, Category::Body),
        VocabEntry::new("骨", "ほね", Pos::Noun, Category::Body),
        VocabEntry::new("皮膚", "ひふ", Pos::Noun, Category::Body),
        VocabEntry::new("髪", "かみ", Pos::Noun, Category::Body),
        VocabEntry::new("唇", "くちびる", Pos::Noun, Category::Body),
        VocabEntry::new("舌", "した", Pos::Noun, Category::Body),
        VocabEntry::new("喉", "のど", Pos::Noun, Category::Body),
        VocabEntry::new("脚", "あし", Pos::Noun, Category::Body),
        VocabEntry::new("膝", "ひざ", Pos::Noun, Category::Body),

        // === PLACE (40 words) ===
        VocabEntry::new("東京", "とうきょう", Pos::Noun, Category::Place),
        VocabEntry::new("京都", "きょうと", Pos::Noun, Category::Place),
        VocabEntry::new("大阪", "おおさか", Pos::Noun, Category::Place),
        VocabEntry::new("北海道", "ほっかいどう", Pos::Noun, Category::Place),
        VocabEntry::new("沖縄", "おきなわ", Pos::Noun, Category::Place),
        VocabEntry::new("日本", "にほん", Pos::Noun, Category::Place),
        VocabEntry::new("学校", "がっこう", Pos::Noun, Category::Place),
        VocabEntry::new("病院", "びょういん", Pos::Noun, Category::Place),
        VocabEntry::new("駅", "えき", Pos::Noun, Category::Place),
        VocabEntry::new("空港", "くうこう", Pos::Noun, Category::Place),
        VocabEntry::new("公園", "こうえん", Pos::Noun, Category::Place),
        VocabEntry::new("図書館", "としょかん", Pos::Noun, Category::Place),
        VocabEntry::new("銀行", "ぎんこう", Pos::Noun, Category::Place),
        VocabEntry::new("郵便局", "ゆうびんきょく", Pos::Noun, Category::Place),
        VocabEntry::new("デパート", "デパート", Pos::Noun, Category::Place),
        VocabEntry::new("コンビニ", "コンビニ", Pos::Noun, Category::Place),
        VocabEntry::new("レストラン", "レストラン", Pos::Noun, Category::Place),
        VocabEntry::new("ホテル", "ホテル", Pos::Noun, Category::Place),
        VocabEntry::new("神社", "じんじゃ", Pos::Noun, Category::Place),
        VocabEntry::new("寺", "てら", Pos::Noun, Category::Place),
        VocabEntry::new("城", "しろ", Pos::Noun, Category::Place),
        VocabEntry::new("橋", "はし", Pos::Noun, Category::Place),
        VocabEntry::new("道", "みち", Pos::Noun, Category::Place),
        VocabEntry::new("町", "まち", Pos::Noun, Category::Place),
        VocabEntry::new("村", "むら", Pos::Noun, Category::Place),
        VocabEntry::new("市", "し", Pos::Noun, Category::Place),
        VocabEntry::new("県", "けん", Pos::Noun, Category::Place),
        VocabEntry::new("国", "くに", Pos::Noun, Category::Place),
        VocabEntry::new("地下鉄駅", "ちかてつえき", Pos::Noun, Category::Place),
        VocabEntry::new("スタジアム", "スタジアム", Pos::Noun, Category::Place),
        VocabEntry::new("映画館", "えいがかん", Pos::Noun, Category::Place),
        VocabEntry::new("劇場", "げきじょう", Pos::Noun, Category::Place),
        VocabEntry::new("商店街", "しょうてんがい", Pos::Noun, Category::Place),
        VocabEntry::new("教会", "きょうかい", Pos::Noun, Category::Place),
        VocabEntry::new("モール", "モール", Pos::Noun, Category::Place),
        VocabEntry::new("オフィス", "オフィス", Pos::Noun, Category::Place),
        VocabEntry::new("工場", "こうじょう", Pos::Noun, Category::Place),
        VocabEntry::new("港", "みなと", Pos::Noun, Category::Place),
        VocabEntry::new("空地", "あきち", Pos::Noun, Category::Place),
        VocabEntry::new("広場", "ひろば", Pos::Noun, Category::Place),

        // === TIME (25 words) ===
        VocabEntry::new("今日", "きょう", Pos::Noun, Category::Time),
        VocabEntry::new("明日", "あした", Pos::Noun, Category::Time),
        VocabEntry::new("昨日", "きのう", Pos::Noun, Category::Time),
        VocabEntry::new("朝", "あさ", Pos::Noun, Category::Time),
        VocabEntry::new("昼", "ひる", Pos::Noun, Category::Time),
        VocabEntry::new("夜", "よる", Pos::Noun, Category::Time),
        VocabEntry::new("夕方", "ゆうがた", Pos::Noun, Category::Time),
        VocabEntry::new("今", "いま", Pos::Noun, Category::Time),
        VocabEntry::new("先週", "せんしゅう", Pos::Noun, Category::Time),
        VocabEntry::new("来週", "らいしゅう", Pos::Noun, Category::Time),
        VocabEntry::new("今月", "こんげつ", Pos::Noun, Category::Time),
        VocabEntry::new("先月", "せんげつ", Pos::Noun, Category::Time),
        VocabEntry::new("来月", "らいげつ", Pos::Noun, Category::Time),
        VocabEntry::new("今年", "ことし", Pos::Noun, Category::Time),
        VocabEntry::new("去年", "きょねん", Pos::Noun, Category::Time),
        VocabEntry::new("来年", "らいねん", Pos::Noun, Category::Time),
        VocabEntry::new("月曜日", "げつようび", Pos::Noun, Category::Time),
        VocabEntry::new("火曜日", "かようび", Pos::Noun, Category::Time),
        VocabEntry::new("水曜日", "すいようび", Pos::Noun, Category::Time),
        VocabEntry::new("木曜日", "もくようび", Pos::Noun, Category::Time),
        VocabEntry::new("金曜日", "きんようび", Pos::Noun, Category::Time),
        VocabEntry::new("土曜日", "どようび", Pos::Noun, Category::Time),
        VocabEntry::new("日曜日", "にちようび", Pos::Noun, Category::Time),
        VocabEntry::new("時間", "じかん", Pos::Noun, Category::Time),
        VocabEntry::new("分", "ふん", Pos::Counter, Category::Time),

        // === TRANSPORT (15 words) ===
        VocabEntry::new("電車", "でんしゃ", Pos::Noun, Category::Transport),
        VocabEntry::new("バス", "バス", Pos::Noun, Category::Transport),
        VocabEntry::new("車", "くるま", Pos::Noun, Category::Transport),
        VocabEntry::new("自転車", "じてんしゃ", Pos::Noun, Category::Transport),
        VocabEntry::new("飛行機", "ひこうき", Pos::Noun, Category::Transport),
        VocabEntry::new("船", "ふね", Pos::Noun, Category::Transport),
        VocabEntry::new("タクシー", "タクシー", Pos::Noun, Category::Transport),
        VocabEntry::new("新幹線", "しんかんせん", Pos::Noun, Category::Transport),
        VocabEntry::new("地下鉄", "ちかてつ", Pos::Noun, Category::Transport),
        VocabEntry::new("バイク", "バイク", Pos::Noun, Category::Transport),
        VocabEntry::new("スケートボード", "スケートボード", Pos::Noun, Category::Transport),
        VocabEntry::new("スクーター", "スクーター", Pos::Noun, Category::Transport),
        VocabEntry::new("ロープウェイ", "ロープウェイ", Pos::Noun, Category::Transport),
        VocabEntry::new("ヘリコプター", "ヘリコプター", Pos::Noun, Category::Transport),
        VocabEntry::new("ボート", "ボート", Pos::Noun, Category::Transport),

        // === WORK (25 words) ===
        VocabEntry::new("会社", "かいしゃ", Pos::Noun, Category::Work),
        VocabEntry::new("仕事", "しごと", Pos::Noun, Category::Work),
        VocabEntry::new("会議", "かいぎ", Pos::Noun, Category::Work),
        VocabEntry::new("資料", "しりょう", Pos::Noun, Category::Work),
        VocabEntry::new("電話", "でんわ", Pos::Noun, Category::Work),
        VocabEntry::new("名刺", "めいし", Pos::Noun, Category::Work),
        VocabEntry::new("上司", "じょうし", Pos::Noun, Category::Work),
        VocabEntry::new("部下", "ぶか", Pos::Noun, Category::Work),
        VocabEntry::new("同僚", "どうりょう", Pos::Noun, Category::Work),
        VocabEntry::new("社長", "しゃちょう", Pos::Noun, Category::Work),
        VocabEntry::new("給料", "きゅうりょう", Pos::Noun, Category::Work),
        VocabEntry::new("プロジェクト", "プロジェクト", Pos::Noun, Category::Work),
        VocabEntry::new("事務所", "じむしょ", Pos::Noun, Category::Work),
        VocabEntry::new("工事", "こうじ", Pos::Noun, Category::Work),
        VocabEntry::new("契約", "けいやく", Pos::Noun, Category::Work),
        VocabEntry::new("取引", "とりひき", Pos::Noun, Category::Work),
        VocabEntry::new("営業", "えいぎょう", Pos::Noun, Category::Work),
        VocabEntry::new("企画", "きかく", Pos::Noun, Category::Work),
        VocabEntry::new("開発", "かいはつ", Pos::Noun, Category::Work),
        VocabEntry::new("製造", "せいぞう", Pos::Noun, Category::Work),
        VocabEntry::new("販売", "はんばい", Pos::Noun, Category::Work),
        VocabEntry::new("経営", "けいえい", Pos::Noun, Category::Work),
        VocabEntry::new("人事", "じんじ", Pos::Noun, Category::Work),
        VocabEntry::new("財務", "ざいむ", Pos::Noun, Category::Work),
        VocabEntry::new("会計", "かいけい", Pos::Noun, Category::Work),

        // === SCHOOL (25 words) ===
        VocabEntry::new("先生", "せんせい", Pos::Noun, Category::School),
        VocabEntry::new("学生", "がくせい", Pos::Noun, Category::School),
        VocabEntry::new("教室", "きょうしつ", Pos::Noun, Category::School),
        VocabEntry::new("授業", "じゅぎょう", Pos::Noun, Category::School),
        VocabEntry::new("試験", "しけん", Pos::Noun, Category::School),
        VocabEntry::new("宿題", "しゅくだい", Pos::Noun, Category::School),
        VocabEntry::new("教科書", "きょうかしょ", Pos::Noun, Category::School),
        VocabEntry::new("ノート", "ノート", Pos::Noun, Category::School),
        VocabEntry::new("鉛筆", "えんぴつ", Pos::Noun, Category::School),
        VocabEntry::new("大学", "だいがく", Pos::Noun, Category::School),
        VocabEntry::new("高校", "こうこう", Pos::Noun, Category::School),
        VocabEntry::new("中学", "ちゅうがく", Pos::Noun, Category::School),
        VocabEntry::new("小学校", "しょうがっこう", Pos::Noun, Category::School),
        VocabEntry::new("卒業", "そつぎょう", Pos::Noun, Category::School),
        VocabEntry::new("入学", "にゅうがく", Pos::Noun, Category::School),
        VocabEntry::new("成績", "せいせき", Pos::Noun, Category::School),
        VocabEntry::new("科目", "かもく", Pos::Noun, Category::School),
        VocabEntry::new("講義", "こうぎ", Pos::Noun, Category::School),
        VocabEntry::new("図書室", "としょしつ", Pos::Noun, Category::School),
        VocabEntry::new("体育館", "たいいくかん", Pos::Noun, Category::School),
        VocabEntry::new("運動場", "うんどうじょう", Pos::Noun, Category::School),
        VocabEntry::new("学園", "がくえん", Pos::Noun, Category::School),
        VocabEntry::new("学位", "がくい", Pos::Noun, Category::School),
        VocabEntry::new("奨学金", "しょうがくきん", Pos::Noun, Category::School),
        VocabEntry::new("研究", "けんきゅう", Pos::Noun, Category::School),

        // === SHOPPING (20 words) ===
        VocabEntry::new("値段", "ねだん", Pos::Noun, Category::Shopping),
        VocabEntry::new("お金", "おかね", Pos::Noun, Category::Shopping),
        VocabEntry::new("財布", "さいふ", Pos::Noun, Category::Shopping),
        VocabEntry::new("カード", "カード", Pos::Noun, Category::Shopping),
        VocabEntry::new("レシート", "レシート", Pos::Noun, Category::Shopping),
        VocabEntry::new("袋", "ふくろ", Pos::Noun, Category::Shopping),
        VocabEntry::new("商品", "しょうひん", Pos::Noun, Category::Shopping),
        VocabEntry::new("セール", "セール", Pos::Noun, Category::Shopping),
        VocabEntry::new("割引", "わりびき", Pos::Noun, Category::Shopping),
        VocabEntry::new("店", "みせ", Pos::Noun, Category::Shopping),
        VocabEntry::new("客", "きゃく", Pos::Noun, Category::Shopping),
        VocabEntry::new("店員", "てんいん", Pos::Noun, Category::Shopping),
        VocabEntry::new("値下げ", "ねさげ", Pos::Noun, Category::Shopping),
        VocabEntry::new("返品", "へんぴん", Pos::Noun, Category::Shopping),
        VocabEntry::new("配達", "はいたつ", Pos::Noun, Category::Shopping),
        VocabEntry::new("送料", "そうりょう", Pos::Noun, Category::Shopping),
        VocabEntry::new("購入", "こうにゅう", Pos::Noun, Category::Shopping),
        VocabEntry::new("販売", "はんばい", Pos::Noun, Category::Shopping),
        VocabEntry::new("品質", "ひんしつ", Pos::Noun, Category::Shopping),
        VocabEntry::new("在庫", "ざいこ", Pos::Noun, Category::Shopping),

        // === HEALTH (20 words) ===
        VocabEntry::new("病気", "びょうき", Pos::Noun, Category::Health),
        VocabEntry::new("風邪", "かぜ", Pos::Noun, Category::Health),
        VocabEntry::new("熱", "ねつ", Pos::Noun, Category::Health),
        VocabEntry::new("薬", "くすり", Pos::Noun, Category::Health),
        VocabEntry::new("医者", "いしゃ", Pos::Noun, Category::Health),
        VocabEntry::new("注射", "ちゅうしゃ", Pos::Noun, Category::Health),
        VocabEntry::new("手術", "しゅじゅつ", Pos::Noun, Category::Health),
        VocabEntry::new("入院", "にゅういん", Pos::Noun, Category::Health),
        VocabEntry::new("怪我", "けが", Pos::Noun, Category::Health),
        VocabEntry::new("痛み", "いたみ", Pos::Noun, Category::Health),
        VocabEntry::new("診察", "しんさつ", Pos::Noun, Category::Health),
        VocabEntry::new("症状", "しょうじょう", Pos::Noun, Category::Health),
        VocabEntry::new("病院", "びょういん", Pos::Noun, Category::Health),
        VocabEntry::new("健康", "けんこう", Pos::Noun, Category::Health),
        VocabEntry::new("ビタミン", "ビタミン", Pos::Noun, Category::Health),
        VocabEntry::new("栄養", "えいよう", Pos::Noun, Category::Health),
        VocabEntry::new("予防", "よぼう", Pos::Noun, Category::Health),
        VocabEntry::new("回復", "かいふく", Pos::Noun, Category::Health),
        VocabEntry::new("治療", "ちりょう", Pos::Noun, Category::Health),
        VocabEntry::new("ストレス", "ストレス", Pos::Noun, Category::Health),

        // === HOBBY (25 words) ===
        VocabEntry::new("映画", "えいが", Pos::Noun, Category::Hobby),
        VocabEntry::new("音楽", "おんがく", Pos::Noun, Category::Hobby),
        VocabEntry::new("写真", "しゃしん", Pos::Noun, Category::Hobby),
        VocabEntry::new("絵", "え", Pos::Noun, Category::Hobby),
        VocabEntry::new("歌", "うた", Pos::Noun, Category::Hobby),
        VocabEntry::new("ゲーム", "ゲーム", Pos::Noun, Category::Hobby),
        VocabEntry::new("サッカー", "サッカー", Pos::Noun, Category::Hobby),
        VocabEntry::new("野球", "やきゅう", Pos::Noun, Category::Hobby),
        VocabEntry::new("テニス", "テニス", Pos::Noun, Category::Hobby),
        VocabEntry::new("水泳", "すいえい", Pos::Noun, Category::Hobby),
        VocabEntry::new("釣り", "つり", Pos::Noun, Category::Hobby),
        VocabEntry::new("旅行", "りょこう", Pos::Noun, Category::Hobby),
        VocabEntry::new("読書", "どくしょ", Pos::Noun, Category::Hobby),
        VocabEntry::new("料理", "りょうり", Pos::Noun, Category::Hobby),
        VocabEntry::new("ダンス", "ダンス", Pos::Noun, Category::Hobby),
        VocabEntry::new("絵画", "かいが", Pos::Noun, Category::Hobby),
        VocabEntry::new("彫刻", "ちょうこく", Pos::Noun, Category::Hobby),
        VocabEntry::new("バレーボール", "バレーボール", Pos::Noun, Category::Hobby),
        VocabEntry::new("バスケットボール", "バスケットボール", Pos::Noun, Category::Hobby),
        VocabEntry::new("ゴルフ", "ゴルフ", Pos::Noun, Category::Hobby),
        VocabEntry::new("スキー", "スキー", Pos::Noun, Category::Hobby),
        VocabEntry::new("コンサート", "コンサート", Pos::Noun, Category::Hobby),
        VocabEntry::new("劇", "げき", Pos::Noun, Category::Hobby),
        VocabEntry::new("芸術", "げいじゅつ", Pos::Noun, Category::Hobby),
        VocabEntry::new("スポーツ", "スポーツ", Pos::Noun, Category::Hobby),

        // === EMOTION (20 words) ===
        VocabEntry::new("嬉しい", "うれしい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("悲しい", "かなしい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("楽しい", "たのしい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("怖い", "こわい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("寂しい", "さびしい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("心配", "しんぱい", Pos::NaAdjective, Category::Emotion),
        VocabEntry::new("幸せ", "しあわせ", Pos::NaAdjective, Category::Emotion),
        VocabEntry::new("怒る", "おこる", Pos::Verb, Category::Emotion),
        VocabEntry::new("驚く", "おどろく", Pos::Verb, Category::Emotion),
        VocabEntry::new("恥ずかしい", "はずかしい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("喜ぶ", "よろこぶ", Pos::Verb, Category::Emotion),
        VocabEntry::new("興奮", "こうふん", Pos::Noun, Category::Emotion),
        VocabEntry::new("落胆", "らくたん", Pos::Noun, Category::Emotion),
        VocabEntry::new("感動", "かんどう", Pos::Noun, Category::Emotion),
        VocabEntry::new("失望", "しつぼう", Pos::Noun, Category::Emotion),
        VocabEntry::new("絶望", "ぜつぼう", Pos::Noun, Category::Emotion),
        VocabEntry::new("期待", "きたい", Pos::Noun, Category::Emotion),
        VocabEntry::new("不安", "ふあん", Pos::NaAdjective, Category::Emotion),
        VocabEntry::new("満足", "まんぞく", Pos::NaAdjective, Category::Emotion),
        VocabEntry::new("愛", "あい", Pos::Noun, Category::Emotion),

        // === ANIMAL (20 words) ===
        VocabEntry::new("犬", "いぬ", Pos::Noun, Category::Animal),
        VocabEntry::new("猫", "ねこ", Pos::Noun, Category::Animal),
        VocabEntry::new("鳥", "とり", Pos::Noun, Category::Animal),
        VocabEntry::new("魚", "さかな", Pos::Noun, Category::Animal),
        VocabEntry::new("馬", "うま", Pos::Noun, Category::Animal),
        VocabEntry::new("牛", "うし", Pos::Noun, Category::Animal),
        VocabEntry::new("豚", "ぶた", Pos::Noun, Category::Animal),
        VocabEntry::new("鶏", "にわとり", Pos::Noun, Category::Animal),
        VocabEntry::new("羊", "ひつじ", Pos::Noun, Category::Animal),
        VocabEntry::new("猿", "さる", Pos::Noun, Category::Animal),
        VocabEntry::new("兎", "うさぎ", Pos::Noun, Category::Animal),
        VocabEntry::new("熊", "くま", Pos::Noun, Category::Animal),
        VocabEntry::new("蛇", "へび", Pos::Noun, Category::Animal),
        VocabEntry::new("虫", "むし", Pos::Noun, Category::Animal),
        VocabEntry::new("蝶", "ちょう", Pos::Noun, Category::Animal),
        VocabEntry::new("蜂", "はち", Pos::Noun, Category::Animal),
        VocabEntry::new("蜘蛛", "くも", Pos::Noun, Category::Animal),
        VocabEntry::new("蟹", "かに", Pos::Noun, Category::Animal),
        VocabEntry::new("貝", "かい", Pos::Noun, Category::Animal),
        VocabEntry::new("鹿", "しか", Pos::Noun, Category::Animal),

        // === COLOR (12 words) ===
        VocabEntry::new("赤", "あか", Pos::Noun, Category::Color),
        VocabEntry::new("青", "あお", Pos::Noun, Category::Color),
        VocabEntry::new("白", "しろ", Pos::Noun, Category::Color),
        VocabEntry::new("黒", "くろ", Pos::Noun, Category::Color),
        VocabEntry::new("緑", "みどり", Pos::Noun, Category::Color),
        VocabEntry::new("黄色", "きいろ", Pos::Noun, Category::Color),
        VocabEntry::new("紫", "むらさき", Pos::Noun, Category::Color),
        VocabEntry::new("茶色", "ちゃいろ", Pos::Noun, Category::Color),
        VocabEntry::new("ピンク", "ピンク", Pos::Noun, Category::Color),
        VocabEntry::new("オレンジ", "オレンジ", Pos::Noun, Category::Color),
        VocabEntry::new("灰色", "はいいろ", Pos::Noun, Category::Color),
        VocabEntry::new("金色", "きんいろ", Pos::Noun, Category::Color),

        // === TECHNOLOGY (15 words) ===
        VocabEntry::new("パソコン", "パソコン", Pos::Noun, Category::Technology),
        VocabEntry::new("携帯", "けいたい", Pos::Noun, Category::Technology),
        VocabEntry::new("インターネット", "インターネット", Pos::Noun, Category::Technology),
        VocabEntry::new("メール", "メール", Pos::Noun, Category::Technology),
        VocabEntry::new("アプリ", "アプリ", Pos::Noun, Category::Technology),
        VocabEntry::new("データ", "データ", Pos::Noun, Category::Technology),
        VocabEntry::new("プログラム", "プログラム", Pos::Noun, Category::Technology),
        VocabEntry::new("ソフトウェア", "ソフトウェア", Pos::Noun, Category::Technology),
        VocabEntry::new("ハードウェア", "ハードウェア", Pos::Noun, Category::Technology),
        VocabEntry::new("キーボード", "キーボード", Pos::Noun, Category::Technology),
        VocabEntry::new("マウス", "マウス", Pos::Noun, Category::Technology),
        VocabEntry::new("画面", "がめん", Pos::Noun, Category::Technology),
        VocabEntry::new("バッテリー", "バッテリー", Pos::Noun, Category::Technology),
        VocabEntry::new("カメラ", "カメラ", Pos::Noun, Category::Technology),
        VocabEntry::new("スピーカー", "スピーカー", Pos::Noun, Category::Technology),

        // === HOME (20 words) ===
        VocabEntry::new("家", "いえ", Pos::Noun, Category::Home),
        VocabEntry::new("部屋", "へや", Pos::Noun, Category::Home),
        VocabEntry::new("台所", "だいどころ", Pos::Noun, Category::Home),
        VocabEntry::new("風呂", "ふろ", Pos::Noun, Category::Home),
        VocabEntry::new("トイレ", "トイレ", Pos::Noun, Category::Home),
        VocabEntry::new("窓", "まど", Pos::Noun, Category::Home),
        VocabEntry::new("ドア", "ドア", Pos::Noun, Category::Home),
        VocabEntry::new("階段", "かいだん", Pos::Noun, Category::Home),
        VocabEntry::new("屋根", "やね", Pos::Noun, Category::Home),
        VocabEntry::new("庭", "にわ", Pos::Noun, Category::Home),
        VocabEntry::new("テーブル", "テーブル", Pos::Noun, Category::Home),
        VocabEntry::new("椅子", "いす", Pos::Noun, Category::Home),
        VocabEntry::new("ベッド", "ベッド", Pos::Noun, Category::Home),
        VocabEntry::new("ソファー", "ソファー", Pos::Noun, Category::Home),
        VocabEntry::new("冷蔵庫", "れいぞうこ", Pos::Noun, Category::Home),
        VocabEntry::new("電子レンジ", "でんしレンジ", Pos::Noun, Category::Home),
        VocabEntry::new("洗濯機", "せんたくき", Pos::Noun, Category::Home),
        VocabEntry::new("掃除", "そうじ", Pos::Noun, Category::Home),
        VocabEntry::new("照明", "しょうめい", Pos::Noun, Category::Home),
        VocabEntry::new("カーテン", "カーテン", Pos::Noun, Category::Home),

        // === CULTURE (20 words) ===
        VocabEntry::new("祭り", "まつり", Pos::Noun, Category::Culture),
        VocabEntry::new("着物", "きもの", Pos::Noun, Category::Culture),
        VocabEntry::new("茶道", "ちゃどう", Pos::Noun, Category::Culture),
        VocabEntry::new("華道", "かどう", Pos::Noun, Category::Culture),
        VocabEntry::new("書道", "しょどう", Pos::Noun, Category::Culture),
        VocabEntry::new("神社", "じんじゃ", Pos::Noun, Category::Culture),
        VocabEntry::new("仏教", "ぶっきょう", Pos::Noun, Category::Culture),
        VocabEntry::new("侍", "さむらい", Pos::Noun, Category::Culture),
        VocabEntry::new("忍者", "にんじゃ", Pos::Noun, Category::Culture),
        VocabEntry::new("相撲", "すもう", Pos::Noun, Category::Culture),
        VocabEntry::new("歌舞伎", "かぶき", Pos::Noun, Category::Culture),
        VocabEntry::new("能", "のう", Pos::Noun, Category::Culture),
        VocabEntry::new("狂言", "きょうげん", Pos::Noun, Category::Culture),
        VocabEntry::new("浮世絵", "うきよえ", Pos::Noun, Category::Culture),
        VocabEntry::new("茶会", "ちゃかい", Pos::Noun, Category::Culture),
        VocabEntry::new("武道", "ぶどう", Pos::Noun, Category::Culture),
        VocabEntry::new("剣道", "けんどう", Pos::Noun, Category::Culture),
        VocabEntry::new("柔道", "じゅうどう", Pos::Noun, Category::Culture),
        VocabEntry::new("空手", "からて", Pos::Noun, Category::Culture),
        VocabEntry::new("文化", "ぶんか", Pos::Noun, Category::Culture),

        // === ABSTRACT (25 words) ===
        VocabEntry::new("時間", "じかん", Pos::Noun, Category::Abstract),
        VocabEntry::new("場所", "ばしょ", Pos::Noun, Category::Abstract),
        VocabEntry::new("理由", "りゆう", Pos::Noun, Category::Abstract),
        VocabEntry::new("方法", "ほうほう", Pos::Noun, Category::Abstract),
        VocabEntry::new("意味", "いみ", Pos::Noun, Category::Abstract),
        VocabEntry::new("問題", "もんだい", Pos::Noun, Category::Abstract),
        VocabEntry::new("答え", "こたえ", Pos::Noun, Category::Abstract),
        VocabEntry::new("考え", "かんがえ", Pos::Noun, Category::Abstract),
        VocabEntry::new("気持ち", "きもち", Pos::Noun, Category::Abstract),
        VocabEntry::new("夢", "ゆめ", Pos::Noun, Category::Abstract),
        VocabEntry::new("未来", "みらい", Pos::Noun, Category::Abstract),
        VocabEntry::new("過去", "かこ", Pos::Noun, Category::Abstract),
        VocabEntry::new("自由", "じゆう", Pos::Noun, Category::Abstract),
        VocabEntry::new("平和", "へいわ", Pos::Noun, Category::Abstract),
        VocabEntry::new("希望", "きぼう", Pos::Noun, Category::Abstract),
        VocabEntry::new("真実", "しんじつ", Pos::Noun, Category::Abstract),
        VocabEntry::new("正義", "せいぎ", Pos::Noun, Category::Abstract),
        VocabEntry::new("勇気", "ゆうき", Pos::Noun, Category::Abstract),
        VocabEntry::new("力", "ちから", Pos::Noun, Category::Abstract),
        VocabEntry::new("美", "び", Pos::Noun, Category::Abstract),
        VocabEntry::new("知識", "ちしき", Pos::Noun, Category::Abstract),
        VocabEntry::new("能力", "のうりょく", Pos::Noun, Category::Abstract),
        VocabEntry::new("才能", "さいのう", Pos::Noun, Category::Abstract),
        VocabEntry::new("人生", "じんせい", Pos::Noun, Category::Abstract),
        VocabEntry::new("運命", "うんめい", Pos::Noun, Category::Abstract),

        // === VERBS GROUP 1 (GODAN) (60 words) ===
        VocabEntry::new("行く", "いく", Pos::Verb, Category::Verb),
        VocabEntry::new("いきます", "いきます", Pos::Verb, Category::Verb),
        VocabEntry::new("帰る", "かえる", Pos::Verb, Category::Verb),
        VocabEntry::new("かえります", "かえります", Pos::Verb, Category::Verb),
        VocabEntry::new("読む", "よむ", Pos::Verb, Category::Verb),
        VocabEntry::new("よみます", "よみます", Pos::Verb, Category::Verb),
        VocabEntry::new("書く", "かく", Pos::Verb, Category::Verb),
        VocabEntry::new("かきます", "かきます", Pos::Verb, Category::Verb),
        VocabEntry::new("話す", "はなす", Pos::Verb, Category::Verb),
        VocabEntry::new("はなします", "はなします", Pos::Verb, Category::Verb),
        VocabEntry::new("聞く", "きく", Pos::Verb, Category::Verb),
        VocabEntry::new("ききます", "ききます", Pos::Verb, Category::Verb),
        VocabEntry::new("飲む", "のむ", Pos::Verb, Category::Verb),
        VocabEntry::new("のみます", "のみます", Pos::Verb, Category::Verb),
        VocabEntry::new("買う", "かう", Pos::Verb, Category::Verb),
        VocabEntry::new("かいます", "かいます", Pos::Verb, Category::Verb),
        VocabEntry::new("待つ", "まつ", Pos::Verb, Category::Verb),
        VocabEntry::new("まちます", "まちます", Pos::Verb, Category::Verb),
        VocabEntry::new("作る", "つくる", Pos::Verb, Category::Verb),
        VocabEntry::new("つくります", "つくります", Pos::Verb, Category::Verb),
        VocabEntry::new("走る", "はしる", Pos::Verb, Category::Verb),
        VocabEntry::new("はしります", "はしります", Pos::Verb, Category::Verb),
        VocabEntry::new("泳ぐ", "およぐ", Pos::Verb, Category::Verb),
        VocabEntry::new("およぎます", "およぎます", Pos::Verb, Category::Verb),
        VocabEntry::new("遊ぶ", "あそぶ", Pos::Verb, Category::Verb),
        VocabEntry::new("あそびます", "あそびます", Pos::Verb, Category::Verb),
        VocabEntry::new("死ぬ", "しぬ", Pos::Verb, Category::Verb),
        VocabEntry::new("しにます", "しにます", Pos::Verb, Category::Verb),
        VocabEntry::new("歩く", "あるく", Pos::Verb, Category::Verb),
        VocabEntry::new("あるきます", "あるきます", Pos::Verb, Category::Verb),
        VocabEntry::new("座る", "すわる", Pos::Verb, Category::Verb),
        VocabEntry::new("すわります", "すわります", Pos::Verb, Category::Verb),
        VocabEntry::new("立つ", "たつ", Pos::Verb, Category::Verb),
        VocabEntry::new("たちます", "たちます", Pos::Verb, Category::Verb),
        VocabEntry::new("乗る", "のる", Pos::Verb, Category::Verb),
        VocabEntry::new("のります", "のります", Pos::Verb, Category::Verb),
        VocabEntry::new("歌う", "うたう", Pos::Verb, Category::Verb),
        VocabEntry::new("うたいます", "うたいます", Pos::Verb, Category::Verb),
        VocabEntry::new("払う", "はらう", Pos::Verb, Category::Verb),
        VocabEntry::new("はらいます", "はらいます", Pos::Verb, Category::Verb),
        VocabEntry::new("持つ", "もつ", Pos::Verb, Category::Verb),
        VocabEntry::new("もちます", "もちます", Pos::Verb, Category::Verb),
        VocabEntry::new("使う", "つかう", Pos::Verb, Category::Verb),
        VocabEntry::new("つかいます", "つかいます", Pos::Verb, Category::Verb),
        VocabEntry::new("送る", "おくる", Pos::Verb, Category::Verb),
        VocabEntry::new("おくります", "おくります", Pos::Verb, Category::Verb),
        VocabEntry::new("届く", "とどく", Pos::Verb, Category::Verb),
        VocabEntry::new("とどきます", "とどきます", Pos::Verb, Category::Verb),
        VocabEntry::new("降りる", "おりる", Pos::Verb, Category::Verb),
        VocabEntry::new("おります", "おります", Pos::Verb, Category::Verb),
        VocabEntry::new("開く", "ひらく", Pos::Verb, Category::Verb),
        VocabEntry::new("ひらきます", "ひらきます", Pos::Verb, Category::Verb),
        VocabEntry::new("閉じる", "とじる", Pos::Verb, Category::Verb),
        VocabEntry::new("とじます", "とじます", Pos::Verb, Category::Verb),
        VocabEntry::new("切る", "きる", Pos::Verb, Category::Verb),
        VocabEntry::new("きります", "きります", Pos::Verb, Category::Verb),
        VocabEntry::new("つかむ", "つかむ", Pos::Verb, Category::Verb),
        VocabEntry::new("つかみます", "つかみます", Pos::Verb, Category::Verb),
        VocabEntry::new("探す", "さがす", Pos::Verb, Category::Verb),
        VocabEntry::new("さがします", "さがします", Pos::Verb, Category::Verb),

        // === VERBS GROUP 2 (ICHIDAN) (40 words) ===
        VocabEntry::new("食べる", "たべる", Pos::Verb, Category::Verb),
        VocabEntry::new("たべます", "たべます", Pos::Verb, Category::Verb),
        VocabEntry::new("見る", "みる", Pos::Verb, Category::Verb),
        VocabEntry::new("みます", "みます", Pos::Verb, Category::Verb),
        VocabEntry::new("起きる", "おきる", Pos::Verb, Category::Verb),
        VocabEntry::new("おきます", "おきます", Pos::Verb, Category::Verb),
        VocabEntry::new("寝る", "ねる", Pos::Verb, Category::Verb),
        VocabEntry::new("ねます", "ねます", Pos::Verb, Category::Verb),
        VocabEntry::new("教える", "おしえる", Pos::Verb, Category::Verb),
        VocabEntry::new("おしえます", "おしえます", Pos::Verb, Category::Verb),
        VocabEntry::new("覚える", "おぼえる", Pos::Verb, Category::Verb),
        VocabEntry::new("おぼえます", "おぼえます", Pos::Verb, Category::Verb),
        VocabEntry::new("出る", "でる", Pos::Verb, Category::Verb),
        VocabEntry::new("でます", "でます", Pos::Verb, Category::Verb),
        VocabEntry::new("入れる", "いれる", Pos::Verb, Category::Verb),
        VocabEntry::new("いれます", "いれます", Pos::Verb, Category::Verb),
        VocabEntry::new("開ける", "あける", Pos::Verb, Category::Verb),
        VocabEntry::new("あけます", "あけます", Pos::Verb, Category::Verb),
        VocabEntry::new("閉める", "しめる", Pos::Verb, Category::Verb),
        VocabEntry::new("しめます", "しめます", Pos::Verb, Category::Verb),
        VocabEntry::new("着る", "きる", Pos::Verb, Category::Verb),
        VocabEntry::new("きます", "きます", Pos::Verb, Category::Verb),
        VocabEntry::new("浴びる", "あびる", Pos::Verb, Category::Verb),
        VocabEntry::new("あびます", "あびます", Pos::Verb, Category::Verb),
        VocabEntry::new("下りる", "おりる", Pos::Verb, Category::Verb),
        VocabEntry::new("おります", "おります", Pos::Verb, Category::Verb),
        VocabEntry::new("調べる", "しらべる", Pos::Verb, Category::Verb),
        VocabEntry::new("しらべます", "しらべます", Pos::Verb, Category::Verb),
        VocabEntry::new("答える", "こたえる", Pos::Verb, Category::Verb),
        VocabEntry::new("こたえます", "こたえます", Pos::Verb, Category::Verb),
        VocabEntry::new("求める", "もとめる", Pos::Verb, Category::Verb),
        VocabEntry::new("もとめます", "もとめます", Pos::Verb, Category::Verb),
        VocabEntry::new("信じる", "しんじる", Pos::Verb, Category::Verb),
        VocabEntry::new("しんじます", "しんじます", Pos::Verb, Category::Verb),
        VocabEntry::new("変える", "かえる", Pos::Verb, Category::Verb),
        VocabEntry::new("かえます", "かえます", Pos::Verb, Category::Verb),
        VocabEntry::new("申し込む", "もうしこむ", Pos::Verb, Category::Verb),
        VocabEntry::new("もうしこみます", "もうしこみます", Pos::Verb, Category::Verb),
        VocabEntry::new("練習する", "れんしゅうする", Pos::Verb, Category::Verb),
        VocabEntry::new("れんしゅうします", "れんしゅうします", Pos::Verb, Category::Verb),

        // === IRREGULAR VERBS (10 words) ===
        VocabEntry::new("する", "する", Pos::Verb, Category::Verb),
        VocabEntry::new("します", "します", Pos::Verb, Category::Verb),
        VocabEntry::new("来る", "くる", Pos::Verb, Category::Verb),
        VocabEntry::new("きます", "きます", Pos::Verb, Category::Verb),
        VocabEntry::new("いる", "いる", Pos::Verb, Category::Verb),
        VocabEntry::new("います", "います", Pos::Verb, Category::Verb),
        VocabEntry::new("ある", "ある", Pos::Verb, Category::Verb),
        VocabEntry::new("あります", "あります", Pos::Verb, Category::Verb),
        VocabEntry::new("なる", "なる", Pos::Verb, Category::Verb),
        VocabEntry::new("なります", "なります", Pos::Verb, Category::Verb),

        // === I-ADJECTIVES (50 words) ===
        VocabEntry::new("大きい", "おおきい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("小さい", "ちいさい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("高い", "たかい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("低い", "ひくい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("長い", "ながい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("短い", "みじかい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("太い", "ふとい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("細い", "ほそい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("新しい", "あたらしい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("古い", "ふるい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("暑い", "あつい", Pos::IAdjective, Category::Time),
        VocabEntry::new("寒い", "さむい", Pos::IAdjective, Category::Time),
        VocabEntry::new("美味しい", "おいしい", Pos::IAdjective, Category::Food),
        VocabEntry::new("美しい", "うつくしい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("怖い", "こわい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("悲しい", "かなしい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("嬉しい", "うれしい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("楽しい", "たのしい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("面白い", "おもしろい", Pos::IAdjective, Category::Hobby),
        VocabEntry::new("つまらない", "つまらない", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("痛い", "いたい", Pos::IAdjective, Category::Health),
        VocabEntry::new("痒い", "かゆい", Pos::IAdjective, Category::Health),
        VocabEntry::new("かわいい", "かわいい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("易しい", "やさしい", Pos::IAdjective, Category::School),
        VocabEntry::new("難しい", "むずかしい", Pos::IAdjective, Category::School),
        VocabEntry::new("多い", "おおい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("少ない", "すくない", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("広い", "ひろい", Pos::IAdjective, Category::Place),
        VocabEntry::new("狭い", "せまい", Pos::IAdjective, Category::Place),
        VocabEntry::new("深い", "ふかい", Pos::IAdjective, Category::Nature),
        VocabEntry::new("浅い", "あさい", Pos::IAdjective, Category::Nature),
        VocabEntry::new("濃い", "こい", Pos::IAdjective, Category::Color),
        VocabEntry::new("薄い", "うすい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("硬い", "かたい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("柔らかい", "やわらかい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("甘い", "あまい", Pos::IAdjective, Category::Food),
        VocabEntry::new("塩辛い", "しおからい", Pos::IAdjective, Category::Food),
        VocabEntry::new("酸っぱい", "すっぱい", Pos::IAdjective, Category::Food),
        VocabEntry::new("苦い", "にがい", Pos::IAdjective, Category::Food),
        VocabEntry::new("安い", "やすい", Pos::IAdjective, Category::Shopping),
        VocabEntry::new("危ない", "あぶない", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("安全", "あんぜん", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("有名", "ゆうめい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("親切", "しんせつ", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("正直", "しょうじき", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("下手", "へた", Pos::IAdjective, Category::Hobby),
        VocabEntry::new("上手", "じょうず", Pos::IAdjective, Category::Hobby),
        VocabEntry::new("強い", "つよい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("弱い", "よわい", Pos::IAdjective, Category::Abstract),

        // === NA-ADJECTIVES (30 words) ===
        VocabEntry::new("綺麗", "きれい", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("静か", "しずか", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("有名", "ゆうめい", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("便利", "べんり", Pos::NaAdjective, Category::Technology),
        VocabEntry::new("大切", "たいせつ", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("元気", "げんき", Pos::NaAdjective, Category::Health),
        VocabEntry::new("好き", "すき", Pos::NaAdjective, Category::Emotion),
        VocabEntry::new("嫌い", "きらい", Pos::NaAdjective, Category::Emotion),
        VocabEntry::new("真面目", "まじめ", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("派手", "はで", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("地味", "じみ", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("馬鹿", "ばか", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("上品", "じょうひん", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("下品", "げひん", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("奇麗", "きれい", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("複雑", "ふくざつ", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("簡単", "かんたん", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("丈夫", "じょうぶ", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("必要", "ひつよう", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("十分", "じゅうぶん", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("無駄", "むだ", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("快適", "かいてき", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("不快", "ふかい", Pos::NaAdjective, Category::Emotion),
        VocabEntry::new("活発", "かっぱつ", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("穏やか", "おだやか", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("危険", "きけん", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("不安", "ふあん", Pos::NaAdjective, Category::Emotion),
        VocabEntry::new("満足", "まんぞく", Pos::NaAdjective, Category::Emotion),
        VocabEntry::new("不満", "ふまん", Pos::NaAdjective, Category::Emotion),
        VocabEntry::new("幸せ", "しあわせ", Pos::NaAdjective, Category::Emotion),

        // === PARTICLES (15 words) ===
        VocabEntry::new("は", "は", Pos::Particle, Category::Particle),
        VocabEntry::new("が", "が", Pos::Particle, Category::Particle),
        VocabEntry::new("を", "を", Pos::Particle, Category::Particle),
        VocabEntry::new("に", "に", Pos::Particle, Category::Particle),
        VocabEntry::new("で", "で", Pos::Particle, Category::Particle),
        VocabEntry::new("と", "と", Pos::Particle, Category::Particle),
        VocabEntry::new("も", "も", Pos::Particle, Category::Particle),
        VocabEntry::new("から", "から", Pos::Particle, Category::Particle),
        VocabEntry::new("まで", "まで", Pos::Particle, Category::Particle),
        VocabEntry::new("の", "の", Pos::Particle, Category::Particle),
        VocabEntry::new("へ", "へ", Pos::Particle, Category::Particle),
        VocabEntry::new("より", "より", Pos::Particle, Category::Particle),
        VocabEntry::new("か", "か", Pos::Particle, Category::Particle),
        VocabEntry::new("ね", "ね", Pos::Particle, Category::Particle),
        VocabEntry::new("よ", "よ", Pos::Particle, Category::Particle),

        // === ADVERBS (25 words) ===
        VocabEntry::new("とても", "とても", Pos::Adverb, Category::Abstract),
        VocabEntry::new("すごく", "すごく", Pos::Adverb, Category::Abstract),
        VocabEntry::new("ちょっと", "ちょっと", Pos::Adverb, Category::Abstract),
        VocabEntry::new("たくさん", "たくさん", Pos::Adverb, Category::Abstract),
        VocabEntry::new("少し", "すこし", Pos::Adverb, Category::Abstract),
        VocabEntry::new("もっと", "もっと", Pos::Adverb, Category::Abstract),
        VocabEntry::new("まだ", "まだ", Pos::Adverb, Category::Time),
        VocabEntry::new("もう", "もう", Pos::Adverb, Category::Time),
        VocabEntry::new("いつも", "いつも", Pos::Adverb, Category::Time),
        VocabEntry::new("時々", "ときどき", Pos::Adverb, Category::Time),
        VocabEntry::new("しばしば", "しばしば", Pos::Adverb, Category::Time),
        VocabEntry::new("たまに", "たまに", Pos::Adverb, Category::Time),
        VocabEntry::new("ずっと", "ずっと", Pos::Adverb, Category::Time),
        VocabEntry::new("急に", "きゅうに", Pos::Adverb, Category::Time),
        VocabEntry::new("ゆっくり", "ゆっくり", Pos::Adverb, Category::Abstract),
        VocabEntry::new("早く", "はやく", Pos::Adverb, Category::Time),
        VocabEntry::new("遅く", "おそく", Pos::Adverb, Category::Time),
        VocabEntry::new("近く", "ちかく", Pos::Adverb, Category::Place),
        VocabEntry::new("遠く", "とおく", Pos::Adverb, Category::Place),
        VocabEntry::new("本当に", "ほんとうに", Pos::Adverb, Category::Abstract),
        VocabEntry::new("恐らく", "おそらく", Pos::Adverb, Category::Abstract),
        VocabEntry::new("確かに", "たしかに", Pos::Adverb, Category::Abstract),
        VocabEntry::new("決して", "けっして", Pos::Adverb, Category::Abstract),
        VocabEntry::new("むしろ", "むしろ", Pos::Adverb, Category::Abstract),
        VocabEntry::new("そろそろ", "そろそろ", Pos::Adverb, Category::Time),

        // === EXPRESSIONS & SUFFIXES (30 words) ===
        VocabEntry::new("です", "です", Pos::Expression, Category::Abstract),
        VocabEntry::new("ます", "ます", Pos::Expression, Category::Abstract),
        VocabEntry::new("ました", "ました", Pos::Expression, Category::Abstract),
        VocabEntry::new("ません", "ません", Pos::Expression, Category::Abstract),
        VocabEntry::new("ませんでした", "ませんでした", Pos::Expression, Category::Abstract),
        VocabEntry::new("ください", "ください", Pos::Expression, Category::Greeting),
        VocabEntry::new("ましょう", "ましょう", Pos::Expression, Category::Abstract),
        VocabEntry::new("たい", "たい", Pos::Suffix, Category::Emotion),
        VocabEntry::new("ない", "ない", Pos::Suffix, Category::Abstract),
        VocabEntry::new("た", "た", Pos::Suffix, Category::Abstract),
        VocabEntry::new("ている", "ている", Pos::Suffix, Category::Abstract),
        VocabEntry::new("ていない", "ていない", Pos::Suffix, Category::Abstract),
        VocabEntry::new("られる", "られる", Pos::Suffix, Category::Abstract),
        VocabEntry::new("させる", "させる", Pos::Suffix, Category::Abstract),
        VocabEntry::new("られた", "られた", Pos::Suffix, Category::Abstract),
        VocabEntry::new("させられる", "させられる", Pos::Suffix, Category::Abstract),
        VocabEntry::new("そうです", "そうです", Pos::Expression, Category::Abstract),
        VocabEntry::new("っぽい", "っぽい", Pos::Suffix, Category::Abstract),
        VocabEntry::new("すぎる", "すぎる", Pos::Suffix, Category::Abstract),
        VocabEntry::new("ぐらい", "ぐらい", Pos::Suffix, Category::Abstract),
        VocabEntry::new("ほど", "ほど", Pos::Suffix, Category::Abstract),
        VocabEntry::new("ような", "ような", Pos::Suffix, Category::Abstract),
        VocabEntry::new("げ", "げ", Pos::Suffix, Category::Abstract),
        VocabEntry::new("気", "け", Pos::Counter, Category::Abstract),
        VocabEntry::new("個", "こ", Pos::Counter, Category::Abstract),
        VocabEntry::new("人", "にん", Pos::Counter, Category::Family),
        VocabEntry::new("台", "だい", Pos::Counter, Category::Abstract),
        VocabEntry::new("冊", "さつ", Pos::Counter, Category::School),
        VocabEntry::new("枚", "まい", Pos::Counter, Category::Abstract),
        VocabEntry::new("本", "ほん", Pos::Counter, Category::Abstract),
    ]
}

/// Filter vocabulary entries by part of speech
pub fn filter_by_pos(vocab: &[VocabEntry], pos: Pos) -> Vec<&VocabEntry> {
    vocab.iter().filter(|entry| entry.pos == pos).collect()
}

/// Filter vocabulary entries by category
pub fn filter_by_category(vocab: &[VocabEntry], category: Category) -> Vec<&VocabEntry> {
    vocab.iter().filter(|entry| entry.category == category).collect()
}

/// Filter vocabulary entries by both POS and category
pub fn filter_by_pos_and_category(
    vocab: &[VocabEntry],
    pos: Pos,
    category: Category,
) -> Vec<&VocabEntry> {
    vocab
        .iter()
        .filter(|entry| entry.pos == pos && entry.category == category)
        .collect()
}

/// Get vocabulary statistics
pub fn get_vocab_stats(vocab: &[VocabEntry]) -> HashMap<Pos, usize> {
    let mut stats = HashMap::new();
    for entry in vocab {
        *stats.entry(entry.pos).or_insert(0) += 1;
    }
    stats
}

/// Build full vocabulary: base (731) + extended (~1200) entries
pub fn build_full_vocab() -> Vec<VocabEntry> {
    let mut vocab = build_vocab();
    vocab.extend(crate::vocab_extended::build_extended_vocab());
    vocab
}

/// Get category statistics
pub fn get_category_stats(vocab: &[VocabEntry]) -> HashMap<Category, usize> {
    let mut stats = HashMap::new();
    for entry in vocab {
        *stats.entry(entry.category).or_insert(0) += 1;
    }
    stats
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_vocab_count() {
        let vocab = build_vocab();
        assert!(vocab.len() >= 700, "Vocabulary should have at least 700 entries, got {}", vocab.len());
    }

    #[test]
    fn test_filter_by_pos() {
        let vocab = build_vocab();
        let nouns = filter_by_pos(&vocab, Pos::Noun);
        assert!(!nouns.is_empty(), "Should have at least some nouns");
    }

    #[test]
    fn test_filter_by_category() {
        let vocab = build_vocab();
        let food = filter_by_category(&vocab, Category::Food);
        assert!(!food.is_empty(), "Should have at least some food items");
    }

    #[test]
    fn test_vocab_entries_valid() {
        let vocab = build_vocab();
        for entry in &vocab {
            assert!(!entry.surface.is_empty(), "Surface form should not be empty");
            assert!(!entry.reading.is_empty(), "Reading should not be empty");
        }
    }
}
