//! Extended Japanese vocabulary (JLPT N5–N3 level).
//! Adds ~2000 entries to the base 731 vocabulary.

use crate::vocab::{Category, Pos, VocabEntry};

/// Build extended vocabulary entries.
pub fn build_extended_vocab() -> Vec<VocabEntry> {
    vec![
        // ============================================================
        // FOOD / DRINK EXTENDED (120 entries)
        // ============================================================
        VocabEntry::new("味噌", "みそ", Pos::Noun, Category::Food),
        VocabEntry::new("醤油", "しょうゆ", Pos::Noun, Category::Food),
        VocabEntry::new("塩", "しお", Pos::Noun, Category::Food),
        VocabEntry::new("砂糖", "さとう", Pos::Noun, Category::Food),
        VocabEntry::new("酢", "す", Pos::Noun, Category::Food),
        VocabEntry::new("胡椒", "こしょう", Pos::Noun, Category::Food),
        VocabEntry::new("米", "こめ", Pos::Noun, Category::Food),
        VocabEntry::new("麦", "むぎ", Pos::Noun, Category::Food),
        VocabEntry::new("小麦", "こむぎ", Pos::Noun, Category::Food),
        VocabEntry::new("大豆", "だいず", Pos::Noun, Category::Food),
        VocabEntry::new("味", "あじ", Pos::Noun, Category::Food),
        VocabEntry::new("弁当", "べんとう", Pos::Noun, Category::Food),
        VocabEntry::new("定食", "ていしょく", Pos::Noun, Category::Food),
        VocabEntry::new("丼", "どんぶり", Pos::Noun, Category::Food),
        VocabEntry::new("焼き鳥", "やきとり", Pos::Noun, Category::Food),
        VocabEntry::new("天ぷら", "てんぷら", Pos::Noun, Category::Food),
        VocabEntry::new("刺身", "さしみ", Pos::Noun, Category::Food),
        VocabEntry::new("味噌汁", "みそしる", Pos::Noun, Category::Food),
        VocabEntry::new("漬物", "つけもの", Pos::Noun, Category::Food),
        VocabEntry::new("煮物", "にもの", Pos::Noun, Category::Food),
        VocabEntry::new("焼き物", "やきもの", Pos::Noun, Category::Food),
        VocabEntry::new("揚げ物", "あげもの", Pos::Noun, Category::Food),
        VocabEntry::new("鍋", "なべ", Pos::Noun, Category::Food),
        VocabEntry::new("蕎麦", "そば", Pos::Noun, Category::Food),
        VocabEntry::new("餅", "もち", Pos::Noun, Category::Food),
        VocabEntry::new("餃子", "ぎょうざ", Pos::Noun, Category::Food),
        VocabEntry::new("焼肉", "やきにく", Pos::Noun, Category::Food),
        VocabEntry::new("牛丼", "ぎゅうどん", Pos::Noun, Category::Food),
        VocabEntry::new("カレー", "カレー", Pos::Noun, Category::Food),
        VocabEntry::new("チャーハン", "チャーハン", Pos::Noun, Category::Food),
        VocabEntry::new("おにぎり", "おにぎり", Pos::Noun, Category::Food),
        VocabEntry::new("梅干し", "うめぼし", Pos::Noun, Category::Food),
        VocabEntry::new("海苔", "のり", Pos::Noun, Category::Food),
        VocabEntry::new("豆腐", "とうふ", Pos::Noun, Category::Food),
        VocabEntry::new("納豆", "なっとう", Pos::Noun, Category::Food),
        VocabEntry::new("枝豆", "えだまめ", Pos::Noun, Category::Food),
        VocabEntry::new("大根", "だいこん", Pos::Noun, Category::Food),
        VocabEntry::new("人参", "にんじん", Pos::Noun, Category::Food),
        VocabEntry::new("玉葱", "たまねぎ", Pos::Noun, Category::Food),
        VocabEntry::new("芋", "いも", Pos::Noun, Category::Food),
        VocabEntry::new("南瓜", "かぼちゃ", Pos::Noun, Category::Food),
        VocabEntry::new("茄子", "なす", Pos::Noun, Category::Food),
        VocabEntry::new("白菜", "はくさい", Pos::Noun, Category::Food),
        VocabEntry::new("菠薐草", "ほうれんそう", Pos::Noun, Category::Food),
        VocabEntry::new("苺", "いちご", Pos::Noun, Category::Food),
        VocabEntry::new("蜜柑", "みかん", Pos::Noun, Category::Food),
        VocabEntry::new("桃", "もも", Pos::Noun, Category::Food),
        VocabEntry::new("梨", "なし", Pos::Noun, Category::Food),
        VocabEntry::new("西瓜", "すいか", Pos::Noun, Category::Food),
        VocabEntry::new("葡萄", "ぶどう", Pos::Noun, Category::Food),
        VocabEntry::new("柿", "かき", Pos::Noun, Category::Food),
        VocabEntry::new("栗", "くり", Pos::Noun, Category::Food),
        VocabEntry::new("鶏肉", "とりにく", Pos::Noun, Category::Food),
        VocabEntry::new("豚肉", "ぶたにく", Pos::Noun, Category::Food),
        VocabEntry::new("牛肉", "ぎゅうにく", Pos::Noun, Category::Food),
        VocabEntry::new("魚", "さかな", Pos::Noun, Category::Food),
        VocabEntry::new("鮭", "さけ", Pos::Noun, Category::Food),
        VocabEntry::new("鯖", "さば", Pos::Noun, Category::Food),
        VocabEntry::new("蟹", "かに", Pos::Noun, Category::Food),
        VocabEntry::new("海老", "えび", Pos::Noun, Category::Food),
        VocabEntry::new("貝", "かい", Pos::Noun, Category::Food),
        VocabEntry::new("水", "みず", Pos::Noun, Category::Food),
        VocabEntry::new("氷", "こおり", Pos::Noun, Category::Food),
        VocabEntry::new("牛乳", "ぎゅうにゅう", Pos::Noun, Category::Food),
        VocabEntry::new("紅茶", "こうちゃ", Pos::Noun, Category::Food),
        VocabEntry::new("緑茶", "りょくちゃ", Pos::Noun, Category::Food),
        VocabEntry::new("珈琲", "コーヒー", Pos::Noun, Category::Food),
        VocabEntry::new("ジュース", "ジュース", Pos::Noun, Category::Food),
        VocabEntry::new("ビール", "ビール", Pos::Noun, Category::Food),
        VocabEntry::new("日本酒", "にほんしゅ", Pos::Noun, Category::Food),
        VocabEntry::new("ワイン", "ワイン", Pos::Noun, Category::Food),
        VocabEntry::new("朝食", "ちょうしょく", Pos::Noun, Category::Food),
        VocabEntry::new("昼食", "ちゅうしょく", Pos::Noun, Category::Food),
        VocabEntry::new("夕食", "ゆうしょく", Pos::Noun, Category::Food),
        VocabEntry::new("間食", "かんしょく", Pos::Noun, Category::Food),
        VocabEntry::new("おかず", "おかず", Pos::Noun, Category::Food),
        VocabEntry::new("デザート", "デザート", Pos::Noun, Category::Food),
        VocabEntry::new("お菓子", "おかし", Pos::Noun, Category::Food),
        VocabEntry::new("飴", "あめ", Pos::Noun, Category::Food),
        VocabEntry::new("チョコレート", "チョコレート", Pos::Noun, Category::Food),

        // ============================================================
        // PLACE / LOCATION EXTENDED (100 entries)
        // ============================================================
        VocabEntry::new("交差点", "こうさてん", Pos::Noun, Category::Place),
        VocabEntry::new("信号", "しんごう", Pos::Noun, Category::Place),
        VocabEntry::new("歩道", "ほどう", Pos::Noun, Category::Place),
        VocabEntry::new("横断歩道", "おうだんほどう", Pos::Noun, Category::Place),
        VocabEntry::new("駐車場", "ちゅうしゃじょう", Pos::Noun, Category::Place),
        VocabEntry::new("空港", "くうこう", Pos::Noun, Category::Place),
        VocabEntry::new("港", "みなと", Pos::Noun, Category::Place),
        VocabEntry::new("市役所", "しやくしょ", Pos::Noun, Category::Place),
        VocabEntry::new("区役所", "くやくしょ", Pos::Noun, Category::Place),
        VocabEntry::new("大使館", "たいしかん", Pos::Noun, Category::Place),
        VocabEntry::new("交番", "こうばん", Pos::Noun, Category::Place),
        VocabEntry::new("消防署", "しょうぼうしょ", Pos::Noun, Category::Place),
        VocabEntry::new("裁判所", "さいばんしょ", Pos::Noun, Category::Place),
        VocabEntry::new("美術館", "びじゅつかん", Pos::Noun, Category::Place),
        VocabEntry::new("博物館", "はくぶつかん", Pos::Noun, Category::Place),
        VocabEntry::new("動物園", "どうぶつえん", Pos::Noun, Category::Place),
        VocabEntry::new("水族館", "すいぞくかん", Pos::Noun, Category::Place),
        VocabEntry::new("遊園地", "ゆうえんち", Pos::Noun, Category::Place),
        VocabEntry::new("映画館", "えいがかん", Pos::Noun, Category::Place),
        VocabEntry::new("体育館", "たいいくかん", Pos::Noun, Category::Place),
        VocabEntry::new("競技場", "きょうぎじょう", Pos::Noun, Category::Place),
        VocabEntry::new("温泉", "おんせん", Pos::Noun, Category::Place),
        VocabEntry::new("銭湯", "せんとう", Pos::Noun, Category::Place),
        VocabEntry::new("旅館", "りょかん", Pos::Noun, Category::Place),
        VocabEntry::new("ホテル", "ホテル", Pos::Noun, Category::Place),
        VocabEntry::new("喫茶店", "きっさてん", Pos::Noun, Category::Place),
        VocabEntry::new("食堂", "しょくどう", Pos::Noun, Category::Place),
        VocabEntry::new("居酒屋", "いざかや", Pos::Noun, Category::Place),
        VocabEntry::new("コンビニ", "コンビニ", Pos::Noun, Category::Place),
        VocabEntry::new("薬局", "やっきょく", Pos::Noun, Category::Place),
        VocabEntry::new("本屋", "ほんや", Pos::Noun, Category::Place),
        VocabEntry::new("花屋", "はなや", Pos::Noun, Category::Place),
        VocabEntry::new("パン屋", "パンや", Pos::Noun, Category::Place),
        VocabEntry::new("魚屋", "さかなや", Pos::Noun, Category::Place),
        VocabEntry::new("八百屋", "やおや", Pos::Noun, Category::Place),
        VocabEntry::new("工場", "こうじょう", Pos::Noun, Category::Place),
        VocabEntry::new("倉庫", "そうこ", Pos::Noun, Category::Place),
        VocabEntry::new("研究所", "けんきゅうじょ", Pos::Noun, Category::Place),
        VocabEntry::new("事務所", "じむしょ", Pos::Noun, Category::Place),
        VocabEntry::new("県", "けん", Pos::Noun, Category::Place),
        VocabEntry::new("市", "し", Pos::Noun, Category::Place),
        VocabEntry::new("町", "まち", Pos::Noun, Category::Place),
        VocabEntry::new("村", "むら", Pos::Noun, Category::Place),
        VocabEntry::new("島", "しま", Pos::Noun, Category::Place),
        VocabEntry::new("半島", "はんとう", Pos::Noun, Category::Place),
        VocabEntry::new("大陸", "たいりく", Pos::Noun, Category::Place),
        VocabEntry::new("地方", "ちほう", Pos::Noun, Category::Place),
        VocabEntry::new("都会", "とかい", Pos::Noun, Category::Place),
        VocabEntry::new("田舎", "いなか", Pos::Noun, Category::Place),
        VocabEntry::new("外国", "がいこく", Pos::Noun, Category::Place),

        // ============================================================
        // BODY / HEALTH EXTENDED (80 entries)
        // ============================================================
        VocabEntry::new("額", "ひたい", Pos::Noun, Category::Body),
        VocabEntry::new("頬", "ほほ", Pos::Noun, Category::Body),
        VocabEntry::new("顎", "あご", Pos::Noun, Category::Body),
        VocabEntry::new("眉", "まゆ", Pos::Noun, Category::Body),
        VocabEntry::new("睫毛", "まつげ", Pos::Noun, Category::Body),
        VocabEntry::new("瞳", "ひとみ", Pos::Noun, Category::Body),
        VocabEntry::new("舌", "した", Pos::Noun, Category::Body),
        VocabEntry::new("歯茎", "はぐき", Pos::Noun, Category::Body),
        VocabEntry::new("喉", "のど", Pos::Noun, Category::Body),
        VocabEntry::new("肩", "かた", Pos::Noun, Category::Body),
        VocabEntry::new("胸", "むね", Pos::Noun, Category::Body),
        VocabEntry::new("背中", "せなか", Pos::Noun, Category::Body),
        VocabEntry::new("腰", "こし", Pos::Noun, Category::Body),
        VocabEntry::new("腹", "はら", Pos::Noun, Category::Body),
        VocabEntry::new("肘", "ひじ", Pos::Noun, Category::Body),
        VocabEntry::new("手首", "てくび", Pos::Noun, Category::Body),
        VocabEntry::new("掌", "てのひら", Pos::Noun, Category::Body),
        VocabEntry::new("爪", "つめ", Pos::Noun, Category::Body),
        VocabEntry::new("太腿", "ふともも", Pos::Noun, Category::Body),
        VocabEntry::new("脛", "すね", Pos::Noun, Category::Body),
        VocabEntry::new("踵", "かかと", Pos::Noun, Category::Body),
        VocabEntry::new("足首", "あしくび", Pos::Noun, Category::Body),
        VocabEntry::new("筋肉", "きんにく", Pos::Noun, Category::Body),
        VocabEntry::new("骨", "ほね", Pos::Noun, Category::Body),
        VocabEntry::new("血", "ち", Pos::Noun, Category::Body),
        VocabEntry::new("血液", "けつえき", Pos::Noun, Category::Body),
        VocabEntry::new("心臓", "しんぞう", Pos::Noun, Category::Body),
        VocabEntry::new("肺", "はい", Pos::Noun, Category::Body),
        VocabEntry::new("胃", "い", Pos::Noun, Category::Body),
        VocabEntry::new("肝臓", "かんぞう", Pos::Noun, Category::Body),
        VocabEntry::new("腎臓", "じんぞう", Pos::Noun, Category::Body),
        VocabEntry::new("脳", "のう", Pos::Noun, Category::Body),
        VocabEntry::new("神経", "しんけい", Pos::Noun, Category::Body),
        VocabEntry::new("皮膚", "ひふ", Pos::Noun, Category::Body),
        VocabEntry::new("汗", "あせ", Pos::Noun, Category::Body),
        VocabEntry::new("涙", "なみだ", Pos::Noun, Category::Body),
        VocabEntry::new("息", "いき", Pos::Noun, Category::Body),
        VocabEntry::new("声", "こえ", Pos::Noun, Category::Body),
        VocabEntry::new("体重", "たいじゅう", Pos::Noun, Category::Body),
        VocabEntry::new("身長", "しんちょう", Pos::Noun, Category::Body),

        // Health
        VocabEntry::new("病気", "びょうき", Pos::Noun, Category::Health),
        VocabEntry::new("怪我", "けが", Pos::Noun, Category::Health),
        VocabEntry::new("傷", "きず", Pos::Noun, Category::Health),
        VocabEntry::new("熱", "ねつ", Pos::Noun, Category::Health),
        VocabEntry::new("咳", "せき", Pos::Noun, Category::Health),
        VocabEntry::new("痛み", "いたみ", Pos::Noun, Category::Health),
        VocabEntry::new("頭痛", "ずつう", Pos::Noun, Category::Health),
        VocabEntry::new("腹痛", "ふくつう", Pos::Noun, Category::Health),
        VocabEntry::new("花粉症", "かふんしょう", Pos::Noun, Category::Health),
        VocabEntry::new("アレルギー", "アレルギー", Pos::Noun, Category::Health),
        VocabEntry::new("手術", "しゅじゅつ", Pos::Noun, Category::Health),
        VocabEntry::new("検査", "けんさ", Pos::Noun, Category::Health),
        VocabEntry::new("治療", "ちりょう", Pos::Noun, Category::Health),
        VocabEntry::new("注射", "ちゅうしゃ", Pos::Noun, Category::Health),
        VocabEntry::new("入院", "にゅういん", Pos::Noun, Category::Health),
        VocabEntry::new("退院", "たいいん", Pos::Noun, Category::Health),
        VocabEntry::new("診察", "しんさつ", Pos::Noun, Category::Health),
        VocabEntry::new("処方箋", "しょほうせん", Pos::Noun, Category::Health),
        VocabEntry::new("健康", "けんこう", Pos::Noun, Category::Health),
        VocabEntry::new("体調", "たいちょう", Pos::Noun, Category::Health),

        // ============================================================
        // NATURE EXTENDED (80 entries)
        // ============================================================
        VocabEntry::new("森", "もり", Pos::Noun, Category::Nature),
        VocabEntry::new("林", "はやし", Pos::Noun, Category::Nature),
        VocabEntry::new("草", "くさ", Pos::Noun, Category::Nature),
        VocabEntry::new("葉", "は", Pos::Noun, Category::Nature),
        VocabEntry::new("枝", "えだ", Pos::Noun, Category::Nature),
        VocabEntry::new("根", "ね", Pos::Noun, Category::Nature),
        VocabEntry::new("種", "たね", Pos::Noun, Category::Nature),
        VocabEntry::new("竹", "たけ", Pos::Noun, Category::Nature),
        VocabEntry::new("松", "まつ", Pos::Noun, Category::Nature),
        VocabEntry::new("梅", "うめ", Pos::Noun, Category::Nature),
        VocabEntry::new("藤", "ふじ", Pos::Noun, Category::Nature),
        VocabEntry::new("菊", "きく", Pos::Noun, Category::Nature),
        VocabEntry::new("百合", "ゆり", Pos::Noun, Category::Nature),
        VocabEntry::new("薔薇", "ばら", Pos::Noun, Category::Nature),
        VocabEntry::new("向日葵", "ひまわり", Pos::Noun, Category::Nature),
        VocabEntry::new("紫陽花", "あじさい", Pos::Noun, Category::Nature),
        VocabEntry::new("桜", "さくら", Pos::Noun, Category::Nature),
        VocabEntry::new("紅葉", "もみじ", Pos::Noun, Category::Nature),
        VocabEntry::new("砂", "すな", Pos::Noun, Category::Nature),
        VocabEntry::new("岩", "いわ", Pos::Noun, Category::Nature),
        VocabEntry::new("崖", "がけ", Pos::Noun, Category::Nature),
        VocabEntry::new("谷", "たに", Pos::Noun, Category::Nature),
        VocabEntry::new("丘", "おか", Pos::Noun, Category::Nature),
        VocabEntry::new("野原", "のはら", Pos::Noun, Category::Nature),
        VocabEntry::new("畑", "はたけ", Pos::Noun, Category::Nature),
        VocabEntry::new("田んぼ", "たんぼ", Pos::Noun, Category::Nature),
        VocabEntry::new("泉", "いずみ", Pos::Noun, Category::Nature),
        VocabEntry::new("滝", "たき", Pos::Noun, Category::Nature),
        VocabEntry::new("沼", "ぬま", Pos::Noun, Category::Nature),
        VocabEntry::new("池", "いけ", Pos::Noun, Category::Nature),
        VocabEntry::new("波", "なみ", Pos::Noun, Category::Nature),
        VocabEntry::new("潮", "しお", Pos::Noun, Category::Nature),
        VocabEntry::new("霜", "しも", Pos::Noun, Category::Nature),
        VocabEntry::new("露", "つゆ", Pos::Noun, Category::Nature),
        VocabEntry::new("虹", "にじ", Pos::Noun, Category::Nature),
        VocabEntry::new("稲妻", "いなずま", Pos::Noun, Category::Nature),
        VocabEntry::new("地震", "じしん", Pos::Noun, Category::Nature),
        VocabEntry::new("噴火", "ふんか", Pos::Noun, Category::Nature),
        VocabEntry::new("洪水", "こうずい", Pos::Noun, Category::Nature),
        VocabEntry::new("干ばつ", "かんばつ", Pos::Noun, Category::Nature),

        // ============================================================
        // ANIMAL EXTENDED (60 entries)
        // ============================================================
        VocabEntry::new("子犬", "こいぬ", Pos::Noun, Category::Animal),
        VocabEntry::new("子猫", "こねこ", Pos::Noun, Category::Animal),
        VocabEntry::new("狼", "おおかみ", Pos::Noun, Category::Animal),
        VocabEntry::new("狐", "きつね", Pos::Noun, Category::Animal),
        VocabEntry::new("狸", "たぬき", Pos::Noun, Category::Animal),
        VocabEntry::new("鹿", "しか", Pos::Noun, Category::Animal),
        VocabEntry::new("猪", "いのしし", Pos::Noun, Category::Animal),
        VocabEntry::new("熊", "くま", Pos::Noun, Category::Animal),
        VocabEntry::new("鯨", "くじら", Pos::Noun, Category::Animal),
        VocabEntry::new("イルカ", "イルカ", Pos::Noun, Category::Animal),
        VocabEntry::new("亀", "かめ", Pos::Noun, Category::Animal),
        VocabEntry::new("蛙", "かえる", Pos::Noun, Category::Animal),
        VocabEntry::new("蛇", "へび", Pos::Noun, Category::Animal),
        VocabEntry::new("蜥蜴", "とかげ", Pos::Noun, Category::Animal),
        VocabEntry::new("鷹", "たか", Pos::Noun, Category::Animal),
        VocabEntry::new("鶴", "つる", Pos::Noun, Category::Animal),
        VocabEntry::new("雀", "すずめ", Pos::Noun, Category::Animal),
        VocabEntry::new("烏", "からす", Pos::Noun, Category::Animal),
        VocabEntry::new("鳩", "はと", Pos::Noun, Category::Animal),
        VocabEntry::new("燕", "つばめ", Pos::Noun, Category::Animal),
        VocabEntry::new("蝶", "ちょう", Pos::Noun, Category::Animal),
        VocabEntry::new("蜂", "はち", Pos::Noun, Category::Animal),
        VocabEntry::new("蟻", "あり", Pos::Noun, Category::Animal),
        VocabEntry::new("蝉", "せみ", Pos::Noun, Category::Animal),
        VocabEntry::new("蛍", "ほたる", Pos::Noun, Category::Animal),
        VocabEntry::new("蜘蛛", "くも", Pos::Noun, Category::Animal),
        VocabEntry::new("虫", "むし", Pos::Noun, Category::Animal),
        VocabEntry::new("鯉", "こい", Pos::Noun, Category::Animal),
        VocabEntry::new("金魚", "きんぎょ", Pos::Noun, Category::Animal),
        VocabEntry::new("鰻", "うなぎ", Pos::Noun, Category::Animal),

        // ============================================================
        // WORK / PROFESSION EXTENDED (80 entries)
        // ============================================================
        VocabEntry::new("社長", "しゃちょう", Pos::Noun, Category::Work),
        VocabEntry::new("部長", "ぶちょう", Pos::Noun, Category::Work),
        VocabEntry::new("課長", "かちょう", Pos::Noun, Category::Work),
        VocabEntry::new("係長", "かかりちょう", Pos::Noun, Category::Work),
        VocabEntry::new("社員", "しゃいん", Pos::Noun, Category::Work),
        VocabEntry::new("同僚", "どうりょう", Pos::Noun, Category::Work),
        VocabEntry::new("上司", "じょうし", Pos::Noun, Category::Work),
        VocabEntry::new("部下", "ぶか", Pos::Noun, Category::Work),
        VocabEntry::new("取引先", "とりひきさき", Pos::Noun, Category::Work),
        VocabEntry::new("営業", "えいぎょう", Pos::Noun, Category::Work),
        VocabEntry::new("経理", "けいり", Pos::Noun, Category::Work),
        VocabEntry::new("総務", "そうむ", Pos::Noun, Category::Work),
        VocabEntry::new("人事", "じんじ", Pos::Noun, Category::Work),
        VocabEntry::new("企画", "きかく", Pos::Noun, Category::Work),
        VocabEntry::new("開発", "かいはつ", Pos::Noun, Category::Work),
        VocabEntry::new("研究", "けんきゅう", Pos::Noun, Category::Work),
        VocabEntry::new("製造", "せいぞう", Pos::Noun, Category::Work),
        VocabEntry::new("品質", "ひんしつ", Pos::Noun, Category::Work),
        VocabEntry::new("納期", "のうき", Pos::Noun, Category::Work),
        VocabEntry::new("予算", "よさん", Pos::Noun, Category::Work),
        VocabEntry::new("利益", "りえき", Pos::Noun, Category::Work),
        VocabEntry::new("損失", "そんしつ", Pos::Noun, Category::Work),
        VocabEntry::new("契約", "けいやく", Pos::Noun, Category::Work),
        VocabEntry::new("報告", "ほうこく", Pos::Noun, Category::Work),
        VocabEntry::new("提案", "ていあん", Pos::Noun, Category::Work),
        VocabEntry::new("交渉", "こうしょう", Pos::Noun, Category::Work),
        VocabEntry::new("出張", "しゅっちょう", Pos::Noun, Category::Work),
        VocabEntry::new("残業", "ざんぎょう", Pos::Noun, Category::Work),
        VocabEntry::new("休暇", "きゅうか", Pos::Noun, Category::Work),
        VocabEntry::new("給料", "きゅうりょう", Pos::Noun, Category::Work),
        VocabEntry::new("賞与", "しょうよ", Pos::Noun, Category::Work),
        VocabEntry::new("昇進", "しょうしん", Pos::Noun, Category::Work),
        VocabEntry::new("転職", "てんしょく", Pos::Noun, Category::Work),
        VocabEntry::new("退職", "たいしょく", Pos::Noun, Category::Work),
        VocabEntry::new("面接", "めんせつ", Pos::Noun, Category::Work),
        VocabEntry::new("履歴書", "りれきしょ", Pos::Noun, Category::Work),
        VocabEntry::new("医者", "いしゃ", Pos::Noun, Category::Work),
        VocabEntry::new("看護師", "かんごし", Pos::Noun, Category::Work),
        VocabEntry::new("弁護士", "べんごし", Pos::Noun, Category::Work),
        VocabEntry::new("警察官", "けいさつかん", Pos::Noun, Category::Work),
        VocabEntry::new("消防士", "しょうぼうし", Pos::Noun, Category::Work),
        VocabEntry::new("運転手", "うんてんしゅ", Pos::Noun, Category::Work),
        VocabEntry::new("料理人", "りょうりにん", Pos::Noun, Category::Work),
        VocabEntry::new("農家", "のうか", Pos::Noun, Category::Work),
        VocabEntry::new("漁師", "りょうし", Pos::Noun, Category::Work),
        VocabEntry::new("大工", "だいく", Pos::Noun, Category::Work),
        VocabEntry::new("画家", "がか", Pos::Noun, Category::Work),
        VocabEntry::new("作家", "さっか", Pos::Noun, Category::Work),
        VocabEntry::new("歌手", "かしゅ", Pos::Noun, Category::Work),
        VocabEntry::new("俳優", "はいゆう", Pos::Noun, Category::Work),

        // ============================================================
        // ABSTRACT / CONCEPT EXTENDED (100 entries)
        // ============================================================
        VocabEntry::new("意見", "いけん", Pos::Noun, Category::Abstract),
        VocabEntry::new("意味", "いみ", Pos::Noun, Category::Abstract),
        VocabEntry::new("理由", "りゆう", Pos::Noun, Category::Abstract),
        VocabEntry::new("原因", "げんいん", Pos::Noun, Category::Abstract),
        VocabEntry::new("結果", "けっか", Pos::Noun, Category::Abstract),
        VocabEntry::new("目的", "もくてき", Pos::Noun, Category::Abstract),
        VocabEntry::new("方法", "ほうほう", Pos::Noun, Category::Abstract),
        VocabEntry::new("問題", "もんだい", Pos::Noun, Category::Abstract),
        VocabEntry::new("答え", "こたえ", Pos::Noun, Category::Abstract),
        VocabEntry::new("質問", "しつもん", Pos::Noun, Category::Abstract),
        VocabEntry::new("説明", "せつめい", Pos::Noun, Category::Abstract),
        VocabEntry::new("例", "れい", Pos::Noun, Category::Abstract),
        VocabEntry::new("種類", "しゅるい", Pos::Noun, Category::Abstract),
        VocabEntry::new("関係", "かんけい", Pos::Noun, Category::Abstract),
        VocabEntry::new("影響", "えいきょう", Pos::Noun, Category::Abstract),
        VocabEntry::new("変化", "へんか", Pos::Noun, Category::Abstract),
        VocabEntry::new("発展", "はってん", Pos::Noun, Category::Abstract),
        VocabEntry::new("進歩", "しんぽ", Pos::Noun, Category::Abstract),
        VocabEntry::new("成功", "せいこう", Pos::Noun, Category::Abstract),
        VocabEntry::new("失敗", "しっぱい", Pos::Noun, Category::Abstract),
        VocabEntry::new("経験", "けいけん", Pos::Noun, Category::Abstract),
        VocabEntry::new("知識", "ちしき", Pos::Noun, Category::Abstract),
        VocabEntry::new("能力", "のうりょく", Pos::Noun, Category::Abstract),
        VocabEntry::new("才能", "さいのう", Pos::Noun, Category::Abstract),
        VocabEntry::new("努力", "どりょく", Pos::Noun, Category::Abstract),
        VocabEntry::new("習慣", "しゅうかん", Pos::Noun, Category::Abstract),
        VocabEntry::new("伝統", "でんとう", Pos::Noun, Category::Abstract),
        VocabEntry::new("文化", "ぶんか", Pos::Noun, Category::Abstract),
        VocabEntry::new("歴史", "れきし", Pos::Noun, Category::Abstract),
        VocabEntry::new("政治", "せいじ", Pos::Noun, Category::Abstract),
        VocabEntry::new("経済", "けいざい", Pos::Noun, Category::Abstract),
        VocabEntry::new("社会", "しゃかい", Pos::Noun, Category::Abstract),
        VocabEntry::new("法律", "ほうりつ", Pos::Noun, Category::Abstract),
        VocabEntry::new("権利", "けんり", Pos::Noun, Category::Abstract),
        VocabEntry::new("義務", "ぎむ", Pos::Noun, Category::Abstract),
        VocabEntry::new("自由", "じゆう", Pos::Noun, Category::Abstract),
        VocabEntry::new("平和", "へいわ", Pos::Noun, Category::Abstract),
        VocabEntry::new("戦争", "せんそう", Pos::Noun, Category::Abstract),
        VocabEntry::new("事故", "じこ", Pos::Noun, Category::Abstract),
        VocabEntry::new("事件", "じけん", Pos::Noun, Category::Abstract),
        VocabEntry::new("情報", "じょうほう", Pos::Noun, Category::Abstract),
        VocabEntry::new("記録", "きろく", Pos::Noun, Category::Abstract),
        VocabEntry::new("計画", "けいかく", Pos::Noun, Category::Abstract),
        VocabEntry::new("準備", "じゅんび", Pos::Noun, Category::Abstract),
        VocabEntry::new("実行", "じっこう", Pos::Noun, Category::Abstract),
        VocabEntry::new("完成", "かんせい", Pos::Noun, Category::Abstract),
        VocabEntry::new("評価", "ひょうか", Pos::Noun, Category::Abstract),
        VocabEntry::new("比較", "ひかく", Pos::Noun, Category::Abstract),
        VocabEntry::new("選択", "せんたく", Pos::Noun, Category::Abstract),
        VocabEntry::new("決定", "けってい", Pos::Noun, Category::Abstract),

        // ============================================================
        // VERBS EXTENDED (200 entries) — Godan
        // ============================================================
        VocabEntry::new("払う", "はらう", Pos::Verb, Category::Verb),
        VocabEntry::new("届く", "とどく", Pos::Verb, Category::Verb),
        VocabEntry::new("届ける", "とどける", Pos::Verb, Category::Verb),
        VocabEntry::new("預かる", "あずかる", Pos::Verb, Category::Verb),
        VocabEntry::new("預ける", "あずける", Pos::Verb, Category::Verb),
        VocabEntry::new("拾う", "ひろう", Pos::Verb, Category::Verb),
        VocabEntry::new("落とす", "おとす", Pos::Verb, Category::Verb),
        VocabEntry::new("壊す", "こわす", Pos::Verb, Category::Verb),
        VocabEntry::new("壊れる", "こわれる", Pos::Verb, Category::Verb),
        VocabEntry::new("直す", "なおす", Pos::Verb, Category::Verb),
        VocabEntry::new("直る", "なおる", Pos::Verb, Category::Verb),
        VocabEntry::new("変える", "かえる", Pos::Verb, Category::Verb),
        VocabEntry::new("変わる", "かわる", Pos::Verb, Category::Verb),
        VocabEntry::new("増える", "ふえる", Pos::Verb, Category::Verb),
        VocabEntry::new("増やす", "ふやす", Pos::Verb, Category::Verb),
        VocabEntry::new("減る", "へる", Pos::Verb, Category::Verb),
        VocabEntry::new("減らす", "へらす", Pos::Verb, Category::Verb),
        VocabEntry::new("集める", "あつめる", Pos::Verb, Category::Verb),
        VocabEntry::new("集まる", "あつまる", Pos::Verb, Category::Verb),
        VocabEntry::new("並ぶ", "ならぶ", Pos::Verb, Category::Verb),
        VocabEntry::new("並べる", "ならべる", Pos::Verb, Category::Verb),
        VocabEntry::new("包む", "つつむ", Pos::Verb, Category::Verb),
        VocabEntry::new("開く", "ひらく", Pos::Verb, Category::Verb),
        VocabEntry::new("閉じる", "とじる", Pos::Verb, Category::Verb),
        VocabEntry::new("押す", "おす", Pos::Verb, Category::Verb),
        VocabEntry::new("引く", "ひく", Pos::Verb, Category::Verb),
        VocabEntry::new("投げる", "なげる", Pos::Verb, Category::Verb),
        VocabEntry::new("捕まえる", "つかまえる", Pos::Verb, Category::Verb),
        VocabEntry::new("握る", "にぎる", Pos::Verb, Category::Verb),
        VocabEntry::new("振る", "ふる", Pos::Verb, Category::Verb),
        VocabEntry::new("触る", "さわる", Pos::Verb, Category::Verb),
        VocabEntry::new("触れる", "ふれる", Pos::Verb, Category::Verb),
        VocabEntry::new("数える", "かぞえる", Pos::Verb, Category::Verb),
        VocabEntry::new("測る", "はかる", Pos::Verb, Category::Verb),
        VocabEntry::new("比べる", "くらべる", Pos::Verb, Category::Verb),
        VocabEntry::new("選ぶ", "えらぶ", Pos::Verb, Category::Verb),
        VocabEntry::new("決める", "きめる", Pos::Verb, Category::Verb),
        VocabEntry::new("決まる", "きまる", Pos::Verb, Category::Verb),
        VocabEntry::new("試す", "ためす", Pos::Verb, Category::Verb),
        VocabEntry::new("確かめる", "たしかめる", Pos::Verb, Category::Verb),
        VocabEntry::new("信じる", "しんじる", Pos::Verb, Category::Verb),
        VocabEntry::new("疑う", "うたがう", Pos::Verb, Category::Verb),
        VocabEntry::new("願う", "ねがう", Pos::Verb, Category::Verb),
        VocabEntry::new("祈る", "いのる", Pos::Verb, Category::Verb),
        VocabEntry::new("諦める", "あきらめる", Pos::Verb, Category::Verb),
        VocabEntry::new("頑張る", "がんばる", Pos::Verb, Category::Verb),
        VocabEntry::new("成功する", "せいこうする", Pos::Verb, Category::Verb),
        VocabEntry::new("失敗する", "しっぱいする", Pos::Verb, Category::Verb),
        VocabEntry::new("参加する", "さんかする", Pos::Verb, Category::Verb),
        VocabEntry::new("出席する", "しゅっせきする", Pos::Verb, Category::Verb),
        VocabEntry::new("欠席する", "けっせきする", Pos::Verb, Category::Verb),
        VocabEntry::new("紹介する", "しょうかいする", Pos::Verb, Category::Verb),
        VocabEntry::new("説明する", "せつめいする", Pos::Verb, Category::Verb),
        VocabEntry::new("連絡する", "れんらくする", Pos::Verb, Category::Verb),
        VocabEntry::new("相談する", "そうだんする", Pos::Verb, Category::Verb),
        VocabEntry::new("賛成する", "さんせいする", Pos::Verb, Category::Verb),
        VocabEntry::new("反対する", "はんたいする", Pos::Verb, Category::Verb),
        VocabEntry::new("注意する", "ちゅういする", Pos::Verb, Category::Verb),
        VocabEntry::new("心配する", "しんぱいする", Pos::Verb, Category::Verb),
        VocabEntry::new("感動する", "かんどうする", Pos::Verb, Category::Verb),
        VocabEntry::new("感謝する", "かんしゃする", Pos::Verb, Category::Verb),
        VocabEntry::new("約束する", "やくそくする", Pos::Verb, Category::Verb),
        VocabEntry::new("予約する", "よやくする", Pos::Verb, Category::Verb),
        VocabEntry::new("運動する", "うんどうする", Pos::Verb, Category::Verb),
        VocabEntry::new("練習する", "れんしゅうする", Pos::Verb, Category::Verb),
        VocabEntry::new("卒業する", "そつぎょうする", Pos::Verb, Category::Verb),
        VocabEntry::new("入学する", "にゅうがくする", Pos::Verb, Category::Verb),
        VocabEntry::new("結婚する", "けっこんする", Pos::Verb, Category::Verb),
        VocabEntry::new("離婚する", "りこんする", Pos::Verb, Category::Verb),
        VocabEntry::new("引っ越す", "ひっこす", Pos::Verb, Category::Verb),
        VocabEntry::new("旅行する", "りょこうする", Pos::Verb, Category::Verb),
        VocabEntry::new("散歩する", "さんぽする", Pos::Verb, Category::Verb),
        VocabEntry::new("掃除する", "そうじする", Pos::Verb, Category::Verb),
        VocabEntry::new("洗濯する", "せんたくする", Pos::Verb, Category::Verb),
        VocabEntry::new("料理する", "りょうりする", Pos::Verb, Category::Verb),
        VocabEntry::new("買い物する", "かいものする", Pos::Verb, Category::Verb),

        // ============================================================
        // I-ADJECTIVES EXTENDED (60 entries)
        // ============================================================
        VocabEntry::new("硬い", "かたい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("柔らかい", "やわらかい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("鋭い", "するどい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("鈍い", "にぶい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("粗い", "あらい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("細かい", "こまかい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("厚い", "あつい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("薄い", "うすい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("濃い", "こい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("淡い", "あわい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("深い", "ふかい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("浅い", "あさい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("広い", "ひろい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("狭い", "せまい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("丸い", "まるい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("四角い", "しかくい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("正しい", "ただしい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("詳しい", "くわしい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("珍しい", "めずらしい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("恥ずかしい", "はずかしい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("羨ましい", "うらやましい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("懐かしい", "なつかしい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("悔しい", "くやしい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("可愛い", "かわいい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("格好いい", "かっこいい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("素晴らしい", "すばらしい", Pos::IAdjective, Category::Emotion),
        VocabEntry::new("激しい", "はげしい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("穏やかい", "おだやかい", Pos::IAdjective, Category::Abstract),
        VocabEntry::new("忙しい", "いそがしい", Pos::IAdjective, Category::Work),
        VocabEntry::new("暇い", "ひまい", Pos::IAdjective, Category::Time),

        // ============================================================
        // NA-ADJECTIVES EXTENDED (40 entries)
        // ============================================================
        VocabEntry::new("便利", "べんり", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("不便", "ふべん", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("丁寧", "ていねい", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("適当", "てきとう", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("正確", "せいかく", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("曖昧", "あいまい", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("複雑", "ふくざつ", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("簡単", "かんたん", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("困難", "こんなん", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("危険", "きけん", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("安全", "あんぜん", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("新鮮", "しんせん", Pos::NaAdjective, Category::Food),
        VocabEntry::new("豊富", "ほうふ", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("貧乏", "びんぼう", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("裕福", "ゆうふく", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("優秀", "ゆうしゅう", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("真面目", "まじめ", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("素直", "すなお", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("勝手", "かって", Pos::NaAdjective, Category::Abstract),
        VocabEntry::new("自然", "しぜん", Pos::NaAdjective, Category::Nature),

        // ============================================================
        // TIME EXTENDED (50 entries)
        // ============================================================
        VocabEntry::new("瞬間", "しゅんかん", Pos::Noun, Category::Time),
        VocabEntry::new("期間", "きかん", Pos::Noun, Category::Time),
        VocabEntry::new("時代", "じだい", Pos::Noun, Category::Time),
        VocabEntry::new("世紀", "せいき", Pos::Noun, Category::Time),
        VocabEntry::new("現在", "げんざい", Pos::Noun, Category::Time),
        VocabEntry::new("過去", "かこ", Pos::Noun, Category::Time),
        VocabEntry::new("未来", "みらい", Pos::Noun, Category::Time),
        VocabEntry::new("将来", "しょうらい", Pos::Noun, Category::Time),
        VocabEntry::new("最近", "さいきん", Pos::Noun, Category::Time),
        VocabEntry::new("以前", "いぜん", Pos::Noun, Category::Time),
        VocabEntry::new("以後", "いご", Pos::Noun, Category::Time),
        VocabEntry::new("当時", "とうじ", Pos::Noun, Category::Time),
        VocabEntry::new("普段", "ふだん", Pos::Noun, Category::Time),
        VocabEntry::new("毎日", "まいにち", Pos::Noun, Category::Time),
        VocabEntry::new("毎週", "まいしゅう", Pos::Noun, Category::Time),
        VocabEntry::new("毎月", "まいつき", Pos::Noun, Category::Time),
        VocabEntry::new("毎年", "まいとし", Pos::Noun, Category::Time),
        VocabEntry::new("一月", "いちがつ", Pos::Noun, Category::Time),
        VocabEntry::new("二月", "にがつ", Pos::Noun, Category::Time),
        VocabEntry::new("三月", "さんがつ", Pos::Noun, Category::Time),
        VocabEntry::new("四月", "しがつ", Pos::Noun, Category::Time),
        VocabEntry::new("五月", "ごがつ", Pos::Noun, Category::Time),
        VocabEntry::new("六月", "ろくがつ", Pos::Noun, Category::Time),
        VocabEntry::new("七月", "しちがつ", Pos::Noun, Category::Time),
        VocabEntry::new("八月", "はちがつ", Pos::Noun, Category::Time),
        VocabEntry::new("九月", "くがつ", Pos::Noun, Category::Time),
        VocabEntry::new("十月", "じゅうがつ", Pos::Noun, Category::Time),
        VocabEntry::new("十一月", "じゅういちがつ", Pos::Noun, Category::Time),
        VocabEntry::new("十二月", "じゅうにがつ", Pos::Noun, Category::Time),
        VocabEntry::new("月曜日", "げつようび", Pos::Noun, Category::Time),
        VocabEntry::new("火曜日", "かようび", Pos::Noun, Category::Time),
        VocabEntry::new("水曜日", "すいようび", Pos::Noun, Category::Time),
        VocabEntry::new("木曜日", "もくようび", Pos::Noun, Category::Time),
        VocabEntry::new("金曜日", "きんようび", Pos::Noun, Category::Time),
        VocabEntry::new("土曜日", "どようび", Pos::Noun, Category::Time),
        VocabEntry::new("日曜日", "にちようび", Pos::Noun, Category::Time),
        VocabEntry::new("正月", "しょうがつ", Pos::Noun, Category::Time),
        VocabEntry::new("誕生日", "たんじょうび", Pos::Noun, Category::Time),
        VocabEntry::new("記念日", "きねんび", Pos::Noun, Category::Time),
        VocabEntry::new("祝日", "しゅくじつ", Pos::Noun, Category::Time),

        // ============================================================
        // HOME / DAILY LIFE EXTENDED (80 entries)
        // ============================================================
        VocabEntry::new("玄関", "げんかん", Pos::Noun, Category::Home),
        VocabEntry::new("廊下", "ろうか", Pos::Noun, Category::Home),
        VocabEntry::new("階段", "かいだん", Pos::Noun, Category::Home),
        VocabEntry::new("屋根", "やね", Pos::Noun, Category::Home),
        VocabEntry::new("壁", "かべ", Pos::Noun, Category::Home),
        VocabEntry::new("天井", "てんじょう", Pos::Noun, Category::Home),
        VocabEntry::new("柱", "はしら", Pos::Noun, Category::Home),
        VocabEntry::new("押入れ", "おしいれ", Pos::Noun, Category::Home),
        VocabEntry::new("棚", "たな", Pos::Noun, Category::Home),
        VocabEntry::new("引き出し", "ひきだし", Pos::Noun, Category::Home),
        VocabEntry::new("鍵", "かぎ", Pos::Noun, Category::Home),
        VocabEntry::new("鏡", "かがみ", Pos::Noun, Category::Home),
        VocabEntry::new("時計", "とけい", Pos::Noun, Category::Home),
        VocabEntry::new("カーテン", "カーテン", Pos::Noun, Category::Home),
        VocabEntry::new("布団", "ふとん", Pos::Noun, Category::Home),
        VocabEntry::new("枕", "まくら", Pos::Noun, Category::Home),
        VocabEntry::new("毛布", "もうふ", Pos::Noun, Category::Home),
        VocabEntry::new("ソファー", "ソファー", Pos::Noun, Category::Home),
        VocabEntry::new("椅子", "いす", Pos::Noun, Category::Home),
        VocabEntry::new("机", "つくえ", Pos::Noun, Category::Home),
        VocabEntry::new("箪笥", "たんす", Pos::Noun, Category::Home),
        VocabEntry::new("冷蔵庫", "れいぞうこ", Pos::Noun, Category::Home),
        VocabEntry::new("電子レンジ", "でんしレンジ", Pos::Noun, Category::Home),
        VocabEntry::new("洗濯機", "せんたくき", Pos::Noun, Category::Home),
        VocabEntry::new("掃除機", "そうじき", Pos::Noun, Category::Home),
        VocabEntry::new("エアコン", "エアコン", Pos::Noun, Category::Home),
        VocabEntry::new("扇風機", "せんぷうき", Pos::Noun, Category::Home),
        VocabEntry::new("ストーブ", "ストーブ", Pos::Noun, Category::Home),
        VocabEntry::new("茶碗", "ちゃわん", Pos::Noun, Category::Home),
        VocabEntry::new("箸", "はし", Pos::Noun, Category::Home),
        VocabEntry::new("皿", "さら", Pos::Noun, Category::Home),
        VocabEntry::new("コップ", "コップ", Pos::Noun, Category::Home),
        VocabEntry::new("包丁", "ほうちょう", Pos::Noun, Category::Home),
        VocabEntry::new("鋏", "はさみ", Pos::Noun, Category::Home),
        VocabEntry::new("針", "はり", Pos::Noun, Category::Home),
        VocabEntry::new("糸", "いと", Pos::Noun, Category::Home),
        VocabEntry::new("紐", "ひも", Pos::Noun, Category::Home),
        VocabEntry::new("袋", "ふくろ", Pos::Noun, Category::Home),
        VocabEntry::new("箱", "はこ", Pos::Noun, Category::Home),
        VocabEntry::new("瓶", "びん", Pos::Noun, Category::Home),

        // ============================================================
        // SCHOOL / EDUCATION EXTENDED (60 entries)
        // ============================================================
        VocabEntry::new("入学", "にゅうがく", Pos::Noun, Category::School),
        VocabEntry::new("卒業", "そつぎょう", Pos::Noun, Category::School),
        VocabEntry::new("進学", "しんがく", Pos::Noun, Category::School),
        VocabEntry::new("留学", "りゅうがく", Pos::Noun, Category::School),
        VocabEntry::new("授業", "じゅぎょう", Pos::Noun, Category::School),
        VocabEntry::new("講義", "こうぎ", Pos::Noun, Category::School),
        VocabEntry::new("試験", "しけん", Pos::Noun, Category::School),
        VocabEntry::new("成績", "せいせき", Pos::Noun, Category::School),
        VocabEntry::new("宿題", "しゅくだい", Pos::Noun, Category::School),
        VocabEntry::new("作文", "さくぶん", Pos::Noun, Category::School),
        VocabEntry::new("教科書", "きょうかしょ", Pos::Noun, Category::School),
        VocabEntry::new("辞書", "じしょ", Pos::Noun, Category::School),
        VocabEntry::new("黒板", "こくばん", Pos::Noun, Category::School),
        VocabEntry::new("チョーク", "チョーク", Pos::Noun, Category::School),
        VocabEntry::new("鉛筆", "えんぴつ", Pos::Noun, Category::School),
        VocabEntry::new("消しゴム", "けしゴム", Pos::Noun, Category::School),
        VocabEntry::new("ノート", "ノート", Pos::Noun, Category::School),
        VocabEntry::new("数学", "すうがく", Pos::Noun, Category::School),
        VocabEntry::new("国語", "こくご", Pos::Noun, Category::School),
        VocabEntry::new("英語", "えいご", Pos::Noun, Category::School),
        VocabEntry::new("理科", "りか", Pos::Noun, Category::School),
        VocabEntry::new("社会科", "しゃかいか", Pos::Noun, Category::School),
        VocabEntry::new("体育", "たいいく", Pos::Noun, Category::School),
        VocabEntry::new("音楽", "おんがく", Pos::Noun, Category::School),
        VocabEntry::new("美術", "びじゅつ", Pos::Noun, Category::School),
        VocabEntry::new("校長", "こうちょう", Pos::Noun, Category::School),
        VocabEntry::new("担任", "たんにん", Pos::Noun, Category::School),
        VocabEntry::new("同級生", "どうきゅうせい", Pos::Noun, Category::School),
        VocabEntry::new("先輩", "せんぱい", Pos::Noun, Category::School),
        VocabEntry::new("後輩", "こうはい", Pos::Noun, Category::School),

        // ============================================================
        // ADVERBS EXTENDED (40 entries)
        // ============================================================
        VocabEntry::new("必ず", "かならず", Pos::Adverb, Category::Abstract),
        VocabEntry::new("決して", "けっして", Pos::Adverb, Category::Abstract),
        VocabEntry::new("絶対", "ぜったい", Pos::Adverb, Category::Abstract),
        VocabEntry::new("多分", "たぶん", Pos::Adverb, Category::Abstract),
        VocabEntry::new("恐らく", "おそらく", Pos::Adverb, Category::Abstract),
        VocabEntry::new("確かに", "たしかに", Pos::Adverb, Category::Abstract),
        VocabEntry::new("実は", "じつは", Pos::Adverb, Category::Abstract),
        VocabEntry::new("実際", "じっさい", Pos::Adverb, Category::Abstract),
        VocabEntry::new("突然", "とつぜん", Pos::Adverb, Category::Abstract),
        VocabEntry::new("急に", "きゅうに", Pos::Adverb, Category::Abstract),
        VocabEntry::new("段々", "だんだん", Pos::Adverb, Category::Abstract),
        VocabEntry::new("次第に", "しだいに", Pos::Adverb, Category::Abstract),
        VocabEntry::new("直ぐ", "すぐ", Pos::Adverb, Category::Abstract),
        VocabEntry::new("既に", "すでに", Pos::Adverb, Category::Abstract),
        VocabEntry::new("未だ", "まだ", Pos::Adverb, Category::Abstract),
        VocabEntry::new("丁度", "ちょうど", Pos::Adverb, Category::Abstract),
        VocabEntry::new("大体", "だいたい", Pos::Adverb, Category::Abstract),
        VocabEntry::new("殆ど", "ほとんど", Pos::Adverb, Category::Abstract),
        VocabEntry::new("全然", "ぜんぜん", Pos::Adverb, Category::Abstract),
        VocabEntry::new("随分", "ずいぶん", Pos::Adverb, Category::Abstract),

        // ============================================================
        // TECHNOLOGY EXTENDED (50 entries)
        // ============================================================
        VocabEntry::new("画面", "がめん", Pos::Noun, Category::Technology),
        VocabEntry::new("電池", "でんち", Pos::Noun, Category::Technology),
        VocabEntry::new("充電", "じゅうでん", Pos::Noun, Category::Technology),
        VocabEntry::new("接続", "せつぞく", Pos::Noun, Category::Technology),
        VocabEntry::new("通信", "つうしん", Pos::Noun, Category::Technology),
        VocabEntry::new("電波", "でんぱ", Pos::Noun, Category::Technology),
        VocabEntry::new("回線", "かいせん", Pos::Noun, Category::Technology),
        VocabEntry::new("データ", "データ", Pos::Noun, Category::Technology),
        VocabEntry::new("ファイル", "ファイル", Pos::Noun, Category::Technology),
        VocabEntry::new("フォルダ", "フォルダ", Pos::Noun, Category::Technology),
        VocabEntry::new("メール", "メール", Pos::Noun, Category::Technology),
        VocabEntry::new("パスワード", "パスワード", Pos::Noun, Category::Technology),
        VocabEntry::new("検索", "けんさく", Pos::Noun, Category::Technology),
        VocabEntry::new("更新", "こうしん", Pos::Noun, Category::Technology),
        VocabEntry::new("設定", "せってい", Pos::Noun, Category::Technology),
        VocabEntry::new("印刷", "いんさつ", Pos::Noun, Category::Technology),
        VocabEntry::new("複写", "ふくしゃ", Pos::Noun, Category::Technology),
        VocabEntry::new("保存", "ほぞん", Pos::Noun, Category::Technology),
        VocabEntry::new("削除", "さくじょ", Pos::Noun, Category::Technology),
        VocabEntry::new("ダウンロード", "ダウンロード", Pos::Noun, Category::Technology),

        // ============================================================
        // FAMILY EXTENDED (30 entries)
        // ============================================================
        VocabEntry::new("家族", "かぞく", Pos::Noun, Category::Family),
        VocabEntry::new("親", "おや", Pos::Noun, Category::Family),
        VocabEntry::new("両親", "りょうしん", Pos::Noun, Category::Family),
        VocabEntry::new("親戚", "しんせき", Pos::Noun, Category::Family),
        VocabEntry::new("夫婦", "ふうふ", Pos::Noun, Category::Family),
        VocabEntry::new("夫", "おっと", Pos::Noun, Category::Family),
        VocabEntry::new("妻", "つま", Pos::Noun, Category::Family),
        VocabEntry::new("息子", "むすこ", Pos::Noun, Category::Family),
        VocabEntry::new("娘", "むすめ", Pos::Noun, Category::Family),
        VocabEntry::new("孫", "まご", Pos::Noun, Category::Family),
        VocabEntry::new("甥", "おい", Pos::Noun, Category::Family),
        VocabEntry::new("姪", "めい", Pos::Noun, Category::Family),
        VocabEntry::new("従兄弟", "いとこ", Pos::Noun, Category::Family),
        VocabEntry::new("義父", "ぎふ", Pos::Noun, Category::Family),
        VocabEntry::new("義母", "ぎぼ", Pos::Noun, Category::Family),

        // ============================================================
        // TRANSPORT EXTENDED (30 entries)
        // ============================================================
        VocabEntry::new("普通列車", "ふつうれっしゃ", Pos::Noun, Category::Transport),
        VocabEntry::new("急行", "きゅうこう", Pos::Noun, Category::Transport),
        VocabEntry::new("特急", "とっきゅう", Pos::Noun, Category::Transport),
        VocabEntry::new("始発", "しはつ", Pos::Noun, Category::Transport),
        VocabEntry::new("終電", "しゅうでん", Pos::Noun, Category::Transport),
        VocabEntry::new("片道", "かたみち", Pos::Noun, Category::Transport),
        VocabEntry::new("往復", "おうふく", Pos::Noun, Category::Transport),
        VocabEntry::new("乗り換え", "のりかえ", Pos::Noun, Category::Transport),
        VocabEntry::new("改札", "かいさつ", Pos::Noun, Category::Transport),
        VocabEntry::new("ホーム", "ホーム", Pos::Noun, Category::Transport),
        VocabEntry::new("切符", "きっぷ", Pos::Noun, Category::Transport),
        VocabEntry::new("定期券", "ていきけん", Pos::Noun, Category::Transport),
        VocabEntry::new("座席", "ざせき", Pos::Noun, Category::Transport),
        VocabEntry::new("指定席", "していせき", Pos::Noun, Category::Transport),
        VocabEntry::new("自由席", "じゆうせき", Pos::Noun, Category::Transport),
        VocabEntry::new("運賃", "うんちん", Pos::Noun, Category::Transport),
        VocabEntry::new("時刻表", "じこくひょう", Pos::Noun, Category::Transport),
        VocabEntry::new("遅延", "ちえん", Pos::Noun, Category::Transport),
        VocabEntry::new("運休", "うんきゅう", Pos::Noun, Category::Transport),
        VocabEntry::new("高速道路", "こうそくどうろ", Pos::Noun, Category::Transport),

        // ============================================================
        // SHOPPING / MONEY EXTENDED (40 entries)
        // ============================================================
        VocabEntry::new("値段", "ねだん", Pos::Noun, Category::Shopping),
        VocabEntry::new("価格", "かかく", Pos::Noun, Category::Shopping),
        VocabEntry::new("割引", "わりびき", Pos::Noun, Category::Shopping),
        VocabEntry::new("税金", "ぜいきん", Pos::Noun, Category::Shopping),
        VocabEntry::new("消費税", "しょうひぜい", Pos::Noun, Category::Shopping),
        VocabEntry::new("領収書", "りょうしゅうしょ", Pos::Noun, Category::Shopping),
        VocabEntry::new("お釣り", "おつり", Pos::Noun, Category::Shopping),
        VocabEntry::new("現金", "げんきん", Pos::Noun, Category::Shopping),
        VocabEntry::new("クレジットカード", "クレジットカード", Pos::Noun, Category::Shopping),
        VocabEntry::new("口座", "こうざ", Pos::Noun, Category::Shopping),
        VocabEntry::new("貯金", "ちょきん", Pos::Noun, Category::Shopping),
        VocabEntry::new("借金", "しゃっきん", Pos::Noun, Category::Shopping),
        VocabEntry::new("家賃", "やちん", Pos::Noun, Category::Shopping),
        VocabEntry::new("光熱費", "こうねつひ", Pos::Noun, Category::Shopping),
        VocabEntry::new("送料", "そうりょう", Pos::Noun, Category::Shopping),
        VocabEntry::new("手数料", "てすうりょう", Pos::Noun, Category::Shopping),
        VocabEntry::new("保険", "ほけん", Pos::Noun, Category::Shopping),
        VocabEntry::new("年金", "ねんきん", Pos::Noun, Category::Shopping),
        VocabEntry::new("売り場", "うりば", Pos::Noun, Category::Shopping),
        VocabEntry::new("試着室", "しちゃくしつ", Pos::Noun, Category::Shopping),

        // ============================================================
        // EMOTION EXTENDED (30 entries)
        // ============================================================
        VocabEntry::new("喜び", "よろこび", Pos::Noun, Category::Emotion),
        VocabEntry::new("怒り", "いかり", Pos::Noun, Category::Emotion),
        VocabEntry::new("悲しみ", "かなしみ", Pos::Noun, Category::Emotion),
        VocabEntry::new("驚き", "おどろき", Pos::Noun, Category::Emotion),
        VocabEntry::new("不安", "ふあん", Pos::Noun, Category::Emotion),
        VocabEntry::new("緊張", "きんちょう", Pos::Noun, Category::Emotion),
        VocabEntry::new("安心", "あんしん", Pos::Noun, Category::Emotion),
        VocabEntry::new("満足", "まんぞく", Pos::Noun, Category::Emotion),
        VocabEntry::new("不満", "ふまん", Pos::Noun, Category::Emotion),
        VocabEntry::new("後悔", "こうかい", Pos::Noun, Category::Emotion),
        VocabEntry::new("期待", "きたい", Pos::Noun, Category::Emotion),
        VocabEntry::new("失望", "しつぼう", Pos::Noun, Category::Emotion),
        VocabEntry::new("興奮", "こうふん", Pos::Noun, Category::Emotion),
        VocabEntry::new("退屈", "たいくつ", Pos::Noun, Category::Emotion),
        VocabEntry::new("感動", "かんどう", Pos::Noun, Category::Emotion),
        VocabEntry::new("同情", "どうじょう", Pos::Noun, Category::Emotion),
        VocabEntry::new("尊敬", "そんけい", Pos::Noun, Category::Emotion),
        VocabEntry::new("軽蔑", "けいべつ", Pos::Noun, Category::Emotion),
        VocabEntry::new("嫉妬", "しっと", Pos::Noun, Category::Emotion),
        VocabEntry::new("愛情", "あいじょう", Pos::Noun, Category::Emotion),
    ]
}
